### ISSUE TITLE
What "highly connected" properties imply a compact sober space is spectral

### ISSUE THREAD

**Issue by david20000813** [pi-base/data#1018]
Continuing the discussion in https://github.com/pi-base/data/pull/919#issuecomment-2512809598, https://github.com/pi-base/data/pull/919#issuecomment-2519600195, and https://github.com/pi-base/data/pull/919#issuecomment-2519994660, where the question is regarding whether [T554](https://topology.pi-base.org/theorems/T000554), "Hereditarily connected + Compact + Sober + Alexandrov => Spectral" can be generalized.

There are currently no known counterexamples in pi-Base to the following two vast generalizations of T554:

["Hyperconnected + Compact + Sober => Spectral"](https://topology.pi-base.org/spaces?q=Hyperconnected+%2B+Compact+%2B+Sober+%2B+not+Spectral)

["Ultraconnected + Compact + Sober => Spectral"](https://topology.pi-base.org/spaces?q=Ultraconnected+%2B+Compact+%2B+Sober+%2B+not+Spectral)

I've just posed an [MSE answer](https://math.stackexchange.com/q/5007859/465145) noting the following:

1. There is already a counterexample to "Hyperconnected + Compact + Sober => Spectral" in pi-Base, namely [S45](https://topology.pi-base.org/spaces/S000045), the overlapping interval topology. It's just that pi-Base currently does not know it is sober, nor does pi-Base know it is not spectral.
2. "Ultraconnected + Compact + Sober => Spectral" is not true either. In fact, even if one adds the Alexandrov condition back in, and requires *both* hyperconnected and ultraconnected, the space is still not necessarily spectral. Indeed, the MSE answer contains a space which is hyperconnected, ultraconnected, compact, sober, and Alexandrov, but not spectral.
3. Dropping Alexandrov without altering hereditarily connected does not work either. The MSE answer contains a space, namely the right open ray topology on $[0,1]$, which is hereditarily connected, compact, and sober, but not spectral.
4. Somewhat surprisingly, if you impose an additional cardinality constraint, then you can actually get it to work. I proved in the MSE answer that "Hereditarily connected + Compact + Sober + Cardinality $< \mathfrak{c}$ => Spectral" is true.
5. I should remark that "Hereditarily connected + Compact + Sober + Cardinality $< \mathfrak{c}$" does *not* imply Alexandrov, so the above cannot be considered as a special case of T554. The easiest counterexample is the right open ray topology on $\omega + 1$, which is hereditarily connected, compact, sober, and countable, but not Alexandrov - there is no minimum open neighborhood of $\omega$.

I'm posting this issue to discuss first what parts of the above the community thinks are interesting to add to pi-Base. The following are my proposed additions:

1. Adding traits to S45 indicating it is sober but not spectral;
2. Adding the space constructed in my MSE answer with the traits that it is hyperconnected, ultraconnected, compact, sober, Alexandrov, and countably infinite, but not spectral;
3. Adding the right open ray topology on $[0,1]$ with the traits that it is hereditarily connected, compact, sober, has cardinality continuum, but not spectral;
4. Related to 3, perhaps also add the right closed ray topology on $[0,1]$? It would be hereditarily connected, compact, has cardinality continuum, Alexandrov, but not sober;
5. Adding a new theorem asserting "Hereditarily connected + Compact + Sober + Cardinality $< \mathfrak{c}$ => Spectral";
6. Adding the right open ray topology on $\omega + 1$ with the traits that it is hereditarily connected, compact, sober, and countably infinite, but not Alexandrov;
7. Related to 6, perhaps also add the right closed ray topology on $\omega + 1$? Maybe also the left ray topology on $\omega + 1$? (The left open and closed ray topologies on $\omega + 1$ are the same, but the right open and closed ray topologies on $\omega + 1$ are different.)

(Of course, I'm not proposing to add these in one PR. Probably 1 and 5 will be part 1, 2 will be part 2, 3 and 4 will be part 3, and 6 and 7 will be part 4, if everything here is going to be added.)

**Comment by prabau** [comment]
I would definitely add 1 and the new theorem from 5.  Does that allow to derive new traits or make some traits redundant?

And also 2, 3, 6 with each new space in its own PR like you suggest.

Then maybe see about 4 and 7 afterwards, comparing with what's already merged.

**Comment by david20000813** [comment]
Completed by various PRs.

**Comment by yhx-12243** [comment]
How about your 4 (right closed ray topology on $[0, 1]$) and 7 (right closed ray topology on $\omega + 1$)? @david20000813

**Comment by GeoffreySangston** [comment]
> How about your 4 (right closed ray topology on [ 0 , 1 ] ) and 7 (right closed ray topology on ω + 1 )? @david20000813

From @david20000813's comment https://github.com/pi-base/data/pull/1103#issuecomment-2547434920

>  the only things not added from #1018 are right closed ray topologies on [ 0 , 1 ] and ω + 1 , neither of which seems to be an interesting example of anything. Unless there's some reason to add those in the future, #1018 can be considered completed.

**Comment by david20000813** [comment]
> How about your 4 (right closed ray topology on [ 0 , 1 ] ) and 7 (right closed ray topology on ω + 1 )? @david20000813

As in my comment quoted by @GeoffreySangston, I simply feel these remaining two spaces are not really interesting examples of anything. They are both just compact, $T_0$, hereditarily connected, Alexandrov, but not sober spaces, and pi-Base already have S150 and S200 as spaces satisfying the said conditions.
