### ISSUE TITLE
Trait Suggestion: Hilbert cube S32 is not Embeddable into Euclidean space P184

### ISSUE THREAD

**Issue by pzjp** [pi-base/data#1029]
## Trait Suggestion

The Hilbert cube [S32](https://topology.pi-base.org/spaces/S000032) is not embeddable into Euclidean space [P184](https://topology.pi-base.org/properties/P000184), but this fact is not known to pi-Base today:
https://topology.pi-base.org/spaces/S000032/properties/P000184

## Proof

This is a consequence of the invariance of domain theorem. Since every Euclidean space (obviosly $(0,1)^n$) can be embedded into a Hilbert cube, its embedding into $\mathbb{R}^m$ would allow a continuous injection of $\mathbb{R}^{m+1}$ into $\mathbb{R}^m$ and consequently an image with empty interior in $\mathbb{R}^{m+1}$.

## Remark
Possibly a property of containg a homeomorphic image of every $\mathbb{R}^m$ could be introduced? Unless no other space (than S32) in the pi-Base satisfies it...

**Comment by prabau** [comment]
I like this argument.

**Comment by prabau** [comment]
@GeoffreySangston @david20000813 I think one of you a while ago used an argument making use of invariance of domain, quoting something from Hatcher maybe, or possibly wikipedia ...  I don't remember exactly.  Would one of you be able to do something similar for this one?

**Comment by Moniker1998** [comment]
It would be enough to observe that $\dim X = \infty$ where $X$ is the Hilbert cube.

This observation alone resolves all the properties P122, P123, P124 and P184 at the same time.

**Comment by prabau** [comment]
Edit: I am the one that used invariance of domain before, in https://topology.pi-base.org/theorems/T000536.

@Moniker1998 I think it's preferable not to use this infinite dimensional characterization for now, for reasons explained in #990.

**Comment by Moniker1998** [comment]
@prabau I don't know what you mean by _characterization_. 

Either way, I am not suggesting to introduce new concepts, but to phrase the proof as the Hilbert cube being infinite-dimensional, and base the arguments around that.

**Comment by GeoffreySangston** [comment]
@Moniker1998 I was actually hoping that one day pi-base might have properties about the three standard dimension functions, and maybe properties about singular homology / cech cohomology etc... Only organically of course. I'm looking forward to someone raising an issue about it so we can all weigh in.

**Comment by prabau** [comment]
Exactly!  We can implicitly use the fact that the space is infinite dimensional without mentioning it.  Basically mention that any nbhd of any point contains subspaces homeomorphic to $\mathbb R^n$ with arbitrary large $n$ and that would contradict invariance of domain, etc.  As suggested in this issue.

**Comment by Moniker1998** [comment]
@GeoffreySangston again, it wouldn't actually be just three concepts, it would be probably six or more of them. Its a project that would require a lot of work

**Comment by prabau** [comment]
> @Moniker1998 I was actually hoping that one day pi-base might have properties about the three standard dimension functions, and maybe properties about singular homology / cech cohomology etc... Only organically of course. I'm looking forward to someone raising an issue about it so we can all weigh in.

All good for the long term, and gradually introduce it.  But not just for this suggestion.

**Comment by prabau** [comment]
> However I think there is a difference between a concept existing on pi-base, and if we are allowed to use that in proofs.

I think that would be a good topic for our monthly zoom discussion.

My take is that if there is an easier argument with concepts already available, it's preferable.  But this should definitely be discussed.

@StevenClontz

**Comment by Moniker1998** [comment]
I think the argument using $\dim [0, 1]^\omega = \infty$ is in fact easier.

If $[0, 1]^\omega$ were embeddable into $\mathbb{R}^n$, then $\dim [0, 1]^\omega \leq \dim \mathbb{R}^n = n$.

Similarly, if $[0, 1]^\omega$ were locally $n$-Euclidean, then we could cover it by countable amount of closed sets $F_i$ with $\dim F_i = n$, so that $\dim [0, 1]^\omega = \sup_i \dim F_i = n$.

**Comment by yhx-12243** [comment]
> I think the argument using d i m ⁡ [ 0 , 1 ] ω = ∞ is in fact easier. Its definitely more conceptual.
> 
> To see that d i m ⁡ [ 0 , 1 ] ω = ∞ note that n = d i m ⁡ [ 0 , 1 ] n ≤ d i m ⁡ [ 0 , 1 ] ω for all n from the subspace theorem.
> 
> If [ 0 , 1 ] ω were embeddable into R n , then d i m ⁡ [ 0 , 1 ] ω ≤ d i m ⁡ R n = n by the subspace theorem.
> 
> Similarly, if [ 0 , 1 ] ω were locally n -Euclidean, then we could cover it by countable amount of closed sets F i with d i m ⁡ F i = n , so that d i m ⁡ [ 0 , 1 ] ω = s u p i d i m ⁡ F i = n by the countable sum theorem.

But this requires dimension theory which is suspended in #990, I think it is the time to open the issue to discuss the dimension theory, which allow to characterize the embeddability of all the subspace in pi-base.

**Comment by Moniker1998** [comment]
@yhx-12243 I don't think you were wrong to use dimension theory in your proofs, although I wouldn't explicitly mention inductive dimension. Its important to note that for separable metric spaces, all usual notions of dimension (small and large inductive, and covering dimension) are the same. I wouldn't distinguish between a particular notion of dimension if $X$ is a separable metric space, and just call it $n$-dimensional, or infinite-dimensional, having in mind that one of those particular properties is meant.

It was the addition of specific properties about dimension theory that I felt like what was @prabau main point, which I agree with.

**Comment by prabau** [comment]
I voted down the above, not because I disagree with the math, but with the approach here.

The results you quote (subspace theorem, etc) seem intuitively plausible.  I personally haven't had the time yet to study dimension theory, except the very basics, enough to know there are a lot of subtleties there.  For people already familiar with that theory, it may indeed be easier to quote these theorems.  But as you explained before, that may require more background than it may seem.  For most of us, the invariance of domain result is still not an easy result, but a lot more well known.  That's why I think it's a preferable approach.

And again, I am all for gradually adding more notions from dimension theory into pi-base.

**Comment by prabau** [comment]
@StevenClontz Issue now added to the agenda for this Friday.

**Comment by Moniker1998** [comment]
> The results you quote (subspace theorem, etc) seem intuitively plausible. I personally haven't had the time yet to study dimension theory, except the very basics, enough to know there are a lot of subtleties there. For people already familiar with that theory, it may indeed be easier to quote these theorems. But as you explained before, that may require more background than it may seem. For most of us, the invariance of domain result is still not an easy result, but a lot more well known. That's why I think it's a preferable approach.

What I meant is that theory for general spaces is complicated, mainly because of the amount of dimension functions that one has to keep track of, the theory for separable metric spaces is straightforward, see e.g.  _Theory of dimensions: Finite and infinite_ by Engelking

What I'd point out is this - is a preference over an approach even needed in the first place?
Nothing stops us from putting two proofs out there.

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/5009117/the-hilbert-cube-cannot-be-embedded-in-some-euclidean-space-mathbb-rn

**Comment by prabau** [comment]
@pzjp Can you add an answer to the mathse post presenting your argument?
I.e., Using invariance of domain without additional dimension theory to show that a space containing a homeomorphic image of every Euclidean space $\mathbb R^n$ cannot be embedded in a specific euclidean space $\mathbb R^m$.

Then we can just refer to that post and we'll have both approaches in a single reference for pi-base.

**Comment by yhx-12243** [comment]
Resolved by #1099.
