### ISSUE TITLE
Theorem Suggestion: Hyperconnected + paracompact => compact

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#1032]
## Theorem Suggestion

If a space is:

- [P39](https://topology.pi-base.org/properties/P000039)
- [P30](https://topology.pi-base.org/properties/P000030)

then it is [P16](https://topology.pi-base.org/properties/P000016).

## Rationale

This theorem would demonstrate that no spaces satisfy the following search:

https://topology.pi-base.org/spaces?q=hyperconnected+%2B+paracompact+%2B+not+compact

This also would show that [S145](https://topology.pi-base.org/spaces/S000145) is not paracompact

## Proof/References

If $\mathcal{U}$ is locally finite open cover of $X$ and $x\in X$ then there exists open $V\subseteq X$ such that $V$ intersects only finitely many members of $\mathcal{U}$. But since $X$ is hyperconnected, $V$ must intersect all of members of $\mathcal{U}$. So any locally finite open cover of $X$ is finite. 

Its now enough for show that if every open cover of $X$ has a finite refinement, then every open cover has a finite subcover. Indeed, suppose that $\\{V_1, ..., V_n\\}$ is a refinement of open cover $\mathcal{U}$. For each $k$ pick $V_k\subseteq U_k$. Then $\\{U_1, ..., U_n\\}$ is a finite subcover of $\mathcal{U}$.

**Comment by prabau** [comment]
Nice result.

**Comment by prabau** [comment]
Wouldn't a similar argument also prove: [Hyperconnected + countably paracompact => compact] ?
