### ISSUE TITLE
Trait Suggestion: Lines with many origins (S83, S84, S85) are semimetrizable.

### ISSUE THREAD

**Issue by pzjp** [pi-base/data#1039]
## Trait Suggestion
The spaces [S83](https://topology.pi-base.org/spaces/S000083), [S84](https://topology.pi-base.org/spaces/S000084) and [S85](https://topology.pi-base.org/spaces/S000085) are semimetrizable [P102](https://topology.pi-base.org/properties/P000102), but this fact is not known to pi-Base today:
https://topology.pi-base.org/properties/P000102/spaces
https://topology.pi-base.org/spaces?q=Semimetrizable%2B%7E%24T_2%24

### Proof
Let $X=\mathbb{R}\backslash\\{0\\} \cup \\{0_\alpha: \alpha\in A\\}$ be a real line with multiple origins. Define a semimetric $d:X^2\to[0,+\infty)$ by
$d(x,y)=|x-y|$, $d(x,0_\alpha)=|x|$, $d(0_\alpha,0_\beta)=1$, $d(0_\alpha,0_\alpha)=0$ for any $x,y\in\mathbb{R}\backslash\\{0\\}$, $\alpha,\beta\in A$, $\alpha\neq\beta$.

Clearly the sets $B_d(x,\epsilon):=\\{y\in X: d(x,y)<\epsilon)\\}$ for $x\in X$ and $\epsilon\in(0,1)$ are a base of topology on $X$. Since they are also open in the semimetric topology, they form a base of the latter as well.

### Comment
Although I expect this fact to be derivable from something more general, we are short on theorems regarding semimetrizability in pi-Base.

**Comment by GeoffreySangston** [comment]
I think [Telophase topology S65](https://topology.pi-base.org/spaces/S000065) should have a semi-metric for the same reason.

**Comment by pzjp** [comment]
Started writting it. Going to create PR (for all 4 spaces) after Christmas.

**Comment by prabau** [comment]
BTW, after #1148 that you are working on, we can ask Steven to give you write access to the official repository, so you can do the work on topic branches from the official repo.  That will be more convenient as there will be automatic builds for every commit, and automatic preview available.

**Comment by pzjp** [comment]
Since the PR #1156 is completed, I'm closing this issue.
