### ISSUE TITLE
Trait Suggestion: Countable bouquet of circles S139 is not Simply connected P200

### ISSUE THREAD

**Issue by GeoffreySangston** [pi-base/data#1043]
## Trait Suggestion

The space Countable bouquet of circles S139 is not Simply connected P200, but this fact is not known to pi-Base today:
[[link to pi-Base]](https://topology.pi-base.org/spaces/S000139/properties/P000200)

## Proof/References

Let $S^1$ denote the quotient of $[0, 1]$ by identifying its endpoints. The map $\mathbb{R} \to S^1$ which sends elements of $\mathbb{Z}$ cosets in the additive group $\mathbb{R}$ to their representative in $[0, 1)$ descends to a retraction $X \to S^1$. Since [Circle is not Simply connected](https://topology.pi-base.org/spaces/S000170/properties/P000200), it follows by Proposition 1.17 of [zbMATH 1044.55001](https://zbmath.org/1044.55001) that $X$ is not simply connected.

**Comment by yhx-12243** [comment]
The complete same argument for S201 (Hawaiian earring).

**Comment by GeoffreySangston** [comment]
The get a continuous retraction $X \to S^1$ the case of S201, the map which is the identity on the biggest circle, and which sends all other points to the intersection point of all the circles is clearly continuous at every point, hence is a continuous retraction.

**Comment by yhx-12243** [comment]
Resolved by #1053.
