### ISSUE TITLE
How to correct description of Gustin's sequence space S122

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#1066]
Blocks #1034, #1035, #1036, #1037, #1038

Months ago I wrote and forgot about https://math.stackexchange.com/questions/4895698/what-separation-axioms-are-held-by-gustins-sequence-space/4896300#4896300 At that time, I claimed we had errata on $\pi$-Base for S122's description, and attempted to write a new characterization of the space.

@Moniker1998 pointed out a few days ago that my recharacterization was flawed - I needed to specify that sequences had even length.

I think I've fixed my recharacterization on MSE (with actually a bit more care than *Counterexamples* about ensuring that neighborhoods only contain even-length sequences). But I'd like feedback on whether we should just fix the characterization we have currently and keep it similar to what is used in *Counterexamples* and used by @Moniker1998 in his MSE answer, or whether my reformulation/answer on MSE is actually preferrable and we should use it on $\pi$-Base instead.

**Comment by Moniker1998** [comment]
I think this boils down to how we define $V_i(n, w)$ and I think either is fine. In the book they defined what $U_i(\alpha)$ is for any sequence of finite length $\alpha$.

**Comment by Moniker1998** [comment]
Other than this - I am not sure what you corrected, it seems to me that your definition and the definition in Counterexamples is precisely the same.

**Comment by StevenClontz** [comment]
Perhaps "recharacterization" isn't the right word; I just prefer to use standard notation for things like $(\omega^2)^{<\omega}$ for a finite sequence of pairs (isomorphic to finite even-length sequence) to help the reader parse things more quickly than writing out definitions in words.

The "correction" needs to be to our S122, which does not specify even length. But I don't like that $U_i(w)$ isn't a subspace of $Y$: it contains sequences of odd length greater than $|w|$, though I guess you can redefine $U_i(w)'=U_i(w)$ and things are fine. I agree that $U_i(\alpha^\frown\langle q(n,w)\rangle)$ is cleaner than the union of  $U_i(\alpha^\frown\langle q(n,w),j\rangle)$s. (Note: I really don't like the weak typing concatenating sequences of ordinals with bare ordinals like $\alpha q(n,w) j$ .)

I guess my other pet peeve is when authors make people think about number theory when they just want a nice injection.

(If no one else has opinions here, then I think the tie goes towards the status quo; fix the error by requiring even length sequences, and start implementing your observations.)

**Comment by Moniker1998** [comment]
> Perhaps "recharacterization" isn't the right word; I just prefer to use standard notation for things like ( ω 2 ) < ω for a finite sequence of pairs (isomorphic to finite even-length sequence) to help the reader parse things more quickly than writing out definitions in words.

Writing $\omega^2$ might be confusing, since $\omega^2$ can be interpreted as an ordinal $\omega\cdot \omega$.

> The "correction" needs to be to our S122, which does not specify even length. But I don't like that U i ( w ) isn't a subspace of Y : it contains sequences of odd length greater than | w | , though I guess you can redefine U i ( w ) ′ = U i ( w ) and things are fine. I agree that U i ( α ⌢ ⟨ q ( n , w ) ⟩ ) is cleaner than the union of U i ( α ⌢ ⟨ q ( n , w ) , j ⟩ ) . (Note: I really don't like the weak typing concatenating sequences of ordinals with bare ordinals like α q ( n , w ) j .)

$U_i(\gamma)$ is always a subspace of $Y$ as per my definitions, and the definitions in Counterexamples! Its a set of those $\alpha\in Y$ that ...

About the notation $\alpha\beta$... I find it easier on the eyes than the $\frown$

**Comment by Moniker1998** [comment]
@StevenClontz Can I start working on Gustin's sequence space, and if so, are you fine with my notation? Or would you rather I use your notation?

**Comment by StevenClontz** [comment]
No one else chimed in, so the tie goes to the status quo I think. I'll make a PR now to make the minor fix (rather than propose my more major shift in notation).
