### ISSUE TITLE
first line of descriptions

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#1086]
> I guess this might be a good place to mention this.
> 
> On [the properties page](https://topology.pi-base.org/properties), cmd + F shows are 6 properties which just give "Any of the following equivalent properties holds:", followed by a block of equivalent definitions. I think we should move the top line of each block to the top.

_Originally posted by @GeoffreySangston in https://github.com/pi-base/web/issues/177#issuecomment-2453839804_

**Comment by GeoffreySangston** [comment]
Just scanned through all of "description text" on the spaces / properties / theorems pages (e.g. https://topology.pi-base.org/spaces/all, etc..). It seems like a nice ideal to strive to make that description text useful in some way, but the only low hanging fruit amenable to improvement seems to be the (now 4) properties with "Any of the following equivalent properties holds".

[Arens square S72](https://topology.pi-base.org/spaces/S000072) unfortunately just displays "Let", which I think everyone would agree doesn't look good. Maybe if pi-base starts displaying images then the top line could be some version of the graphic from Steen-Seebach, which would still convey nonsense, but maybe attractive nonsense. I doubt there's a way to fix it for now and it's not a big deal, so probably nothing should be done.

**Comment by StevenClontz** [comment]
I think #1087 is a strict improvement for S72. I'll also swing at all the  "Any of the following equivalent properties holds" examples now.
