### ISSUE TITLE
Normality of the countable box products of Reals

### ISSUE THREAD

**Issue by gb-solis** [pi-base/data#117]
Hello, I was browsing the site when I noticed it said the countable box product of reals was a normal space (https://topology.pi-base.org/spaces/S000107/properties/P000013)

It struck me as odd for, as far as I knew, this hadn't been proven. 
In fact, I found a [math stackexchange answer](https://math.stackexchange.com/questions/164178/is-mathbbr-omega-a-completely-normal-space-in-the-box-topology) which quotes from the 5th exercise, section 3.2, of Munkres' "Topology" as follows:

> It is not known whether R^ω is normal in the box topology. Mary-Ellen Rudin has shown that the answer is affirmative if one assumes the continuum hypothesis [RM]. In fact, she shows it satisfies a stronger condition called paracompactness.
> 
> [RM] M. E. Rudin. The box product of countably many compact metric spaces. General Topology and Its Applications , 2:293-298, 1972.

Pi-base seems to have jumped to this conclusion based on the premise that it is T5 (https://topology.pi-base.org/spaces/S000107/properties/P000008).

**Comment by StevenClontz** [comment]
Thanks for reporting this error.

> See item #2 for space #109 in DOI 10.1007/978-1-4612-6290-9_6.

I checked this, and it's asserting that the space is T3.5, not T5. So it should assert P000006, not P000008.

**Comment by gb-solis** [comment]
Not at all, I'm happy to help.

While we're at it, I found a typo in the space's description. It seemed straightforward to fix, so I've submitted a pull request.

Keep up the good work!

**Comment by prabau** [comment]
T_4 is not known for the countable box product of reals.  But the answer in https://math.stackexchange.com/questions/3039316/is-mathbbr-omega-endowed-with-the-box-topology-completely-normal-or-hered gives a link to an article by Erik van Douwen (Fund. Math. 88 (1975), 127-132) http://matwbn.icm.edu.pl/ksiazki/fm/fm88/fm88113.pdf showing that the space is definitely *not* T_5.

So if someone wants to add the T_3.5 property, it would be good to change the T_5 property to false at the same time.
