### ISSUE TITLE
The rational numbers are not hemicompact

### ISSUE THREAD

**Issue by Camarneiro** [pi-base/data#151]
The rational numbers are not hemicompact, and are thus an example of a space which is σ-compact, but not hemicompact. The database has no counterexample for this combination.

Source: Eric Wofsey (https://math.stackexchange.com/users/86856/eric-wofsey), A $\sigma$-compact but not hemicompact space?, URL (version: 2021-07-28): https://math.stackexchange.com/q/4209326

**Comment by StevenClontz** [comment]
Thanks! This result is implied by your suggestion in #152 so I'm closing this.
