### ISSUE TITLE
Theorem: hemicompact + first countable implies weakly locally compact

### ISSUE THREAD

**Issue by Camarneiro** [pi-base/data#152]
Theorem: hemicompact + first countable implies weakly locally compact

Source: Henno Brandsma (https://math.stackexchange.com/users/4280/henno-brandsma), A first countable hemicompact space is locally compact, URL (version: 2018-09-16): https://math.stackexchange.com/q/2919068

**Comment by StevenClontz** [comment]
Looks good to me, I've opened a PR in #153 for someone else to confirm before merging.
