### ISSUE TITLE
Introduce locally compact Hausdorff as a property

### ISSUE THREAD

**Issue by prabau** [pi-base/data#157]
We usually try to eliminate redundancies in pi-base, but sometimes it helps to organize things to have a separate name for a related combined property (T3 vs. regular, T4 vs. normal, etc).  I think it would be beneficial to add "locally compact Hausdorff" (LCH) as a property.  They are many locally compact variants, but they all coincide in the Hausdorff case.  Also many theorems involve the combination "weakly locally compact + T2" (see https://topology.pi-base.org/properties/P000023) and could be simplified accordingly.  Comments?

**Comment by StevenClontz** [comment]
I'm interested in a more general discussion: when is it reasonable to add a new property to the pi-Base when the property is known to be a combination of existing properties? I think the answer might be "that combination shows up in enough theorems", as you say for "weakly locally compact + T2". Or the answer might be "as long as it's used in the literature, it's fine".

I think I lean towards the latter, at least for the short-term - actually I guess my real answer to the above question is "whatever is easist for helping folks make contributions and for us to review them", and if you think adding LCH does this then I'm okay with it.

(Aside: one might argue that we shouldn't have any redundant properties; if the definition of P is exactly Q+R, then maybe P should just be an "alias property" and handled differently, but that's an infrastructure change that's lower priority than other work I think.)

**Comment by StevenClontz** [comment]
Another argument in favor: a user searches for "LCH" now, and finds nothing. We cannot add it as an alias as it's not quite either "hausdorff" or "locally compact".

**Comment by prabau** [comment]
I'll come up with something for LCH that you guys can review.

As for the general question you raise about when to add properties that are combinations of other properties, "as long as it's used in the literature" may be a little too broad for my taste.  People add new names to the literature all the time and not all of them have the same importance.  But  if a combination of properties occurs repeatedly and leads to an interesting theory with numerous relations (theorems) with other properties, and adding the combination leads to some economy of expression when expressing these relations, I think that would be a good candidate for adding it.

Not quite related, but I'd like to also note that pi-base currently contains properties that seem to have just dropped from the sky, sometimes without a single related theorem or example space.  Really low priority, but if the properties are worth it, it would be nice to flesh that out at some point.

**Comment by StevenClontz** [comment]
I"m sure there are some stale properties from years gone by - I'd prefer to flesh them out than delete them, to avoid needing to reintroduce them later if they do become more relevant. (I could quite possibly be the culprit; I recall maybe adding some stuff related to my dissertation once upon a time.)

**Comment by prabau** [comment]
There are more subtleties than I realized before taking a look at this.  It seems we can tidy up many of the relationships between the various locally compact related definitions.  Currently we have the following properties:
- (WLC) Weakly locally compact
- (LC) Locally compact
- (LRC) Locally relatively compact = (WLCC) Weakly locally closed-and-compact

Something we did not have is: 
- (LCC) Locally closed-and-compact = each point has a local base of closed and compact nbhds.

But LCC spaces are exactly the spaces that are WLC and regular.  That's a result in Kelley.  See condition (4) in https://en.wikipedia.org/wiki/Locally_compact_space and the refs in the corresponding paragraph.

Being LCC implies both LC and LRC.

In the other direction, locally compact Hausdorff spaces are completely regular. And so are WLC regular spaces (again a result in Kelley).  But we can unify those two by introducing the notion of _preregular_ space (https://en.wikipedia.org/wiki/Preregular_space), which generalizes both Hausdorff and regular, and looks like it could be useful in more than this context.  WLC preregular spaces are completely regular (see refs in the LC wikipedia article).

So I'd like to propose the following plan:
1. add preregular as a property
2. add various theorems showing the relationships between all locally compact related properties
3. add LCH (locally compact Hausdorff)

How does that sound?

**Comment by prabau** [comment]
See https://topology.pi-base.org/properties/P000023. After all the changes above, there only remain two theorems involving Weakly locally compact (WLC) and T2:
- (T196) WLC + T2 ==> Cech complete
- (T269) WLC + T2 + totally disconnected ==> zero dimensional

We can't meaningfully generalize them by replacing T2 by a weaker condition, as Cech complete spaces are T2 by definition.  And for T269, totally disconnected implies T1, so if we assume regular instead of T2, we get back to T2 anyway.  And WLC + totally disconnected alone do not imply zero dimensional, as seen [here](https://topology.pi-base.org/spaces?q=Weakly%20Locally%20Compact%2Btotally%2B~zero).

One could still introduce the LCH property later on, but I feel less urgency to do so at the moment.  So unless you have further comments on this topic, I am inclined to close this issue for now.

**Comment by prabau** [comment]
Actually, one question about https://topology.pi-base.org/properties/P000025. $\sigma$-locally compact is defined as "$\sigma$-compact and locally compact".  But that was the old terminology before Steven replaced "locally compact" with "weakly locally compact" (issue #42).  It seems that this fell through the cracks.  We should change the text in P25 to "$\sigma$-compact and weakly locally compact".  What about the name $\sigma$-locally compact itself?

**Comment by StevenClontz** [comment]
I'd eliminate the property altogether if it wasn't in *Counterexamples* since it's a simple conjunction of two properties, and it violates the pattern \sigma-P = countable union of P.

I don't have a good suggestion for a better name but for now at least the description should be fixed.

**Comment by StevenClontz** [comment]
Is it true that P25 is equivalent to X=\bigcup_{n\in\omega} K_n, where for each x\in X there's n\in\omega such that K_n is a compact neighborhood of x?

**Comment by StevenClontz** [comment]
According to https://en.wikipedia.org/wiki/Hemicompact_space and https://topology.pi-base.org/theorems/T000236 weakly locally compact and Lindelof (implied by sigma-compact) imply hemicompact. So the answer to my question is yes: P25 implies hemicompact, so for each x pick its compact neighborhood H_x by weak local compactness, then H_x is a subset of some K_n by hemicompactness.

So I'll update my PR with my suggested name (but feel free to suggest a better one).

**Comment by prabau** [comment]
> I'd eliminate the property altogether if it wasn't in _Counterexamples_ since it's a simple conjunction of two properties, and it violates the pattern \sigma-P = countable union of P.

Yes, I agree.  Always found the name confusing.

**Comment by prabau** [comment]
I need to give some thought to your proposal for P25.

**Comment by prabau** [comment]
Regarding property [P25](https://topology.pi-base.org/properties/P000025), here are some equivalent characterizations, as far as I can tell.

(1) Weakly locally compact + $\sigma$-compact (= the definition in pi-base).

(2) Weakly locally compact + Lindelof

(3) $X$ can be written as a countable union of compact sets such that each point $x\in X$ has at least one of the compact sets as nbhd. (= your characterization above, with suggested name $\sigma$-neighborhood-compact. I am not sure I like the name, as it is actually stronger than saying $X$ is a countable union of compact neighborhoods (of some points, all points? Not quite matching the $\sigma$-P pattern.)

(4) $X$ can be written as a countable union of interiors of compact subsets. (= same as (3) but without mentioning points. Possible name: $\sigma$-compact-interiors, $\sigma$-interior-of-compact.  I don't like these names.)

(5) $X$ can be written as a union of an increasing sequence of compact sets, each contained in the interior of the next one: $X=\cup_{n\in\omega}K_n$ with each $K_n$ compact and $K_n\subseteq\operatorname{int}(K_{n+1})$.  (This matches the notion of [exhaustion by compact sets](https://en.wikipedia.org/wiki/Exhaustion_by_compact_subsets). Possible name: "exhaustible by compacts").

**Comment by StevenClontz** [comment]
> exhaustible by compacts

:+1:

**Comment by prabau** [comment]
Not introducing LCH for the time being, so closing this issue now.
