### ISSUE TITLE
Perfectly Normal Spaces are not necessarily $G_\delta$

### ISSUE THREAD

**Issue by Samer-Assaf** [pi-base/data#164]
In Pi-Base, it is coded that any perfectly normal space is $G_\delta$ space. This is not necessarily true for all non $T_1$ spaces.

One of the counterexamples is the right ordered reals found [here](https://topology.jdabbs.com/spaces/S000042/properties) this space is perfectly normal since there are no non-trivial disjoint closed sets. This space is not $G_\delta$ since any open set is of the form $(a, +\infty)$ and any closed set is of the form $(-\infty, a]$.

**Comment by prabau** [comment]
Thanks for your comment.  Take a look at the definition of [perfectly normal space](https://topology.pi-base.org/properties/P000015).  There are three equivalent formulations, per Vedenissoff's theorem.  In particular the first one says basically that disjoint closed sets can be "precisely separated" by a function.  But it does not phrased in terms of "disjoint **nonempty** closed sets", as you seem to assume. It is important to allow the case of one of the sets being an empty set, and that's what allows to conclude that any closed set is a G-delta set.

A space like the right ordered reals is ultraconnected (any two nonempty closed sets meet), which implies it is normal.  But you cannot conclude from that that it is perfectly normal.  As you correctly observed, it is not perfectly normal.

**Comment by Samer-Assaf** [comment]
oh yes thx, I missed that distinction.

**Comment by StevenClontz** [comment]
This would be a good contribution - it looks like we don't assert anything that shows S42 is not perfectly normal.

**Comment by prabau** [comment]
@Samer-Assaf Would you be able to submit a pull request for this?

**Comment by prabau** [comment]
@StevenClontz @ccaruvana Actually, maybe we don't need to add a trait file for this.  Instead, it can be deduced from a new theorem:
- Perfectly normal ==> Completely regular.

See https://math.stackexchange.com/questions/4525139/perfectly-normal-spaces-are-completely-regular. I was planning to add this as some point, but was waiting on other things first.  And was also debating whether we should go with that, or introduce the general notion of R0 space and then make use of the two results (see mathse link):
- Perfectly normal ==> R0
- R0 + normal ==> completely regular.

What do you guys think?

**Comment by prabau** [comment]
Thinking about it some more, it's nor really helpful to introduce R0 for this purpose. Showing perfectly normal implies completely regular is pretty simple, and compl. regular implies R0 anyway.

I'll add a pull request.

**Comment by Samer-Assaf** [comment]
> @StevenClontz @ccaruvana Actually, maybe we don't need to add a trait file for this. Instead, it can be deduced from a new theorem:
> 
>     * Perfectly normal ==> Completely regular.
> 
> 
> See https://math.stackexchange.com/questions/4525139/perfectly-normal-spaces-are-completely-regular. I was planning to add this as some point, but was waiting on other things first. And was also debating whether we should go with that, or introduce the general notion of R0 space and then make use of the two results (see mathse link):
> 
>     * Perfectly normal ==> R0
> 
>     * R0 + normal ==> completely regular.
> 
> 
> What do you guys think?


If  I am not mistaken, $G_\delta \Rightarrow R_0$. Here is a shorthanded proof.
Consider a $G_\delta$ topological space $(X,\mathcal{T})$ and let $x, y \in X$ be distinguishable points. W.L.O.G. we take O to be an open neighborhood of $x$ not containing $y$. Since $X\setminus O$ is a closed set and $(X,\mathcal{T})$ is $G_\delta$ space, there is a countable collection of open sets $\{V_i\}_{i\in \mathbb{N}}$ such that $\bigcap_{i\in \mathbb{N}} V_i = X\setminus O$. Now given that $y\in X\setminus O$ and $x\notin X\setminus O$, there is an $i\in \mathbb{N}; y\in V_i and x\notin V_i$ making $(X,\mathcal{T})$ an $R_0$ space.

Something similar has been stated in [this paper](https://www.sciencedirect.com/science/article/abs/pii/S0166864121003667) by Mykhaylyuk et. al. They proved that any $G_\delta$ partial metric space, which is essentially $T_0$, is $T_1$.

**Comment by prabau** [comment]
Nice generalization. Your proof looks right to me.  Let's see what @StevenClontz and @ccaruvana think about how we should approach all this for pi-base.

**Comment by Samer-Assaf** [comment]
@StevenClontz, @ccaruvana, @prabau you guys are more experienced in what works for Pi-base and what doesn't.
But if you decide not to add the notion of $R_0$ yet, might I suggest you still add the theorem $G_\delta +T_0 \Rightarrow T_1$ ? you can quote Mykhaylyuk et. al's paper and say that it is similar. I know I will be adding some of those properties in the current paper I am writing since it deals with some normalities in partial metric spaces.

**Comment by prabau** [comment]
@Samer-Assaf Personally, I think it would be good to have the R0 property.  Let's see what the others say.  In any case, results we add in pi-base usually need to have at least a reference to some published source, or to math stackexchange or mathoverflow.  (As @StevenClontz likes to mention, pi-base is not in the business of peer-reviewing mathematics, but of reflecting peer-reviewed mathematics.) Would you be able to add the result $G_{\delta} \Rightarrow R_0$ to mathse, so that we can have something we can refer to when adding it to pi-base?

**Comment by StevenClontz** [comment]
I think any property listed at https://en.wikipedia.org/wiki/Separation_axiom#Main_definitions is noteworthy enough for pi-Base, so adding R0 is fine with me. I also agree that we should post the justification of theorems to math.SE so they get more air than they will in this thread.

**Comment by prabau** [comment]
Cool.  I'll add a PR for the R0 property that you guys can look at.

@Samer-Assaf Sorry, I should have asked first if you had a user account on mathse.  If you don't, not a problem, I can ask the question G-delta space ==> R0 over there.  Just let me know what you prefer.

**Comment by Samer-Assaf** [comment]
@prabau no problem, all good. Feel free to post it. I am also adding it in my next paper as it pertains to the topic.

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/4547643/g-delta-spaces-are-r-0

**Comment by prabau** [comment]
The name _preregular_ is nice because it makes it easy to remember that regular spaces are preregular.  And it's the main name used [here](https://en.wikipedia.org/wiki/T1_space) and in Schechter for example.  On the other hand, R1 is nice because it implies R1 spaces are R0 and there is some symmetry between R0/T1 and R1/T2.  Is it more commonly used in papers?  I would be ok either way, if you guys have a strong preference.

**Comment by Samer-Assaf** [comment]
@prabau my main pause over preregular is that it may be a bit confusing for new students. Given that $T_0+R_1\Rightarrow T_2$ and not $T_3$.

**Comment by prabau** [comment]
> @prabau my main pause over preregular is that it may be a bit confusing for new students. Given that T0+R1⇒T2 and not T3.

Good point.  @StevenClontz @ccaruvana ?

**Comment by Samer-Assaf** [comment]
Hey, thank you so much for this constructive conversation!
I see that @prabau has opened a pull request with what we discussed.
Would everyone be okay if I closed this post ?
