### ISSUE TITLE
Flesh out P136

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#179]
https://topology.pi-base.org/properties/P000136 - compact subsets are finite

First we should add the alias "anticompact" used here: https://math.stackexchange.com/questions/517411/in-a-topological-space-only-finite-subsets-are-compact-sets

That source also suggests two theorems that will propagate the property in pi-base: every discrete space is p136, and T1 first countable p136 spaces are discrete.

We can also add every finite space is p136. I don't relish having finite spaces being both "compact" and "anticompact" so I don't suggest we change the canonical name for p136 in pi base, barring a lot of literature on the subject using the term I'm unfamiliar with.

I'll tackle this when I'm at a proper computer later this week.

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/1409825 and the reference cited there for the origin of the name, it seems.

**Comment by StevenClontz** [comment]
Of course, discrete spaces are T1 first-countable, so I don't need to make a separate theorem for this.

**Comment by StevenClontz** [comment]
pi-Base caught me on my error, fixing now...
