### ISSUE TITLE
Need to introduce the Empty property

### ISSUE THREAD

**Issue by prabau** [pi-base/data#182]
I was wondering why pi-base was claiming that the Empty space was not meager: https://topology.pi-base.org/spaces/S000163/properties/P000056. It's because of T134 (Baire implies not meager).  That result is generally true, except when the space is empty.

So we could fix this by introducing "empty" as a property.  Would not be too onerous to do, as it would be implied by "has distinct points", and we would just add explicit traits for the Empty space and the Singleton.  Does that sound reasonable?

**Comment by StevenClontz** [comment]
sounds reasonable
