### ISSUE TITLE
Hjalmar Ekdal rename?

### ISSUE THREAD

**Issue by prabau** [pi-base/data#187]
The name [Hjalmar Ekdal topology](https://topology.pi-base.org/spaces/S000047) is rather obscure, especially since it came about as an inside joke (see https://proofwiki.org/wiki/Definition:Hjalmar_Ekdal_Topology).

I was wondering if it would be possible to change the primary name to "Countable sum of Sierpinski spaces".  And at the same time add the anticompact property for example.

**Comment by StevenClontz** [comment]
As long as the name from *Counterexamples* is left as an alias, this is fine with me.
