### ISSUE TITLE
License.md

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#2]
We should add clarity on how the license applies to the data in this repo, and how it applies to contributions to this repo.

**Comment by StevenClontz** [comment]
We say we're using CC 4.0 BY, but have the Share-Alike version copypasta'd into the repo. This conflict should be fixed; I think for our own flexibility in using user contributions, we don't want to require Share-Alike.

**Comment by jamesdabbs** [comment]
I think I thought it was already CC 4.0 BY? That was my intention. In any case, feel free to update the license as you see fit.
