### ISSUE TITLE
Examples of Hausdorff non-regular P-spaces which are and aren't Urysohn

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#220]
A P-space is a space for which every G_delta set is open (there's a lot of different concepts under the same name).
In this article https://www.sciencedirect.com/science/article/pii/0016660X72900268 on page 352, example 3.1 they provide two examples, both of Hausdorff non-regular P-spaces, one which is Urysohn, and another which isn't.
The article also contains other properties relating to P-spaces

**Comment by StevenClontz** [comment]
Thanks! Noting a few things for a future pull request implementing this...

- I think P-space is not in pi-base, contrast with [P000132](https://topology.pi-base.org/properties/P000132)
- I believe both examples in Example 3.1 are not in pi-base.

**Comment by prabau** [comment]
Hi @Moniker1998. We have added the P-space property and the two examples you suggested to pi-base.  Nice addition.  As you mentioned, the article also contains other theorems involving P-space, that we did not get to.  Feel free to contribute pull requests to some of those and we will be very happy to review them and incorporate them.

**Comment by StevenClontz** [comment]
Closing in the meantime, we can reopen or make a new issue for further contributions related to this paper.
