### ISSUE TITLE
Tracking issue for redundant theorems

### ISSUE THREAD

**Issue by prabau** [pi-base/data#232]
Some theorems are redundant in the sense that they are deducible from combinations of other theorems.  It was suggested that it would be beneficial to remove them.  On the other hand there may be some drawbacks in doing so.  See the discussion in #168 in particular.

Until we get a general (technical or otherwise) resolution to this we can use comments below to track redundant theorems.  That will make it easier to keep track of them.

**Comment by prabau** [comment]
T197 (Finite + T1 ==> discrete) is redundant, as consequence of
- (T266) Finite ==> Alexandrov
- (T267) Alexandrov + T1 ==> discrete.

T236 (WLC + Lindelof ==> hemicompact) is redundant.  See comments in #209.

**Comment by StevenClontz** [comment]
If there's a proposal for a syntax for describing redundancies in YAML frontmatter, such as

```
deprecatedBy:
  - T000266
  - T000267
```

there's nothing stopping us from making the annotations now, even if they aren't implemented in the viewer for a while.

**Comment by prabau** [comment]
That seems like a good idea.  It would be searchable, so we don't need to keep track of them here.  We can discuss at our next zoom meeting.
