### ISSUE TITLE
Temporary added workflow for merging contributions

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#245]
@jamesdabbs and I are working on a new version of the pi-base viewer application. We hoped to push it to production already, but there have been some issues.

As a result, I pre-emptively updated this data repo to use `main` instead of `master`. This is more conventional these days, but the new viewer that knows `main` is, well, the "main" branch instead of `master` has been delayed.

Temporary fix: after each updated to `main`, delete the `master` branch at https://github.com/pi-base/data/branches . Then visit https://github.dev/pi-base/data and create a new `master` branch using the bottom toolbar, which will make `master` an exact copy of `main`.

**Comment by StevenClontz** [comment]
tagging @prabau @ccaruvana

**Comment by StevenClontz** [comment]
Example: #247

**Comment by prabau** [comment]
Thanks for the updated "temporary fix".  Easy to use.

**Comment by jamesdabbs** [comment]
I _do_ think we're getting close on the cutover, but please let me know if this is workaround is a non-trivial amount of toil, and we can address it directly.

**Comment by StevenClontz** [comment]
not worth your time - if it took you 20 minutes I'd rather that go towards the cutover instead. :-)

**Comment by StevenClontz** [comment]
closed as topology.pi-base.org is updated
