### ISSUE TITLE
edit math.stackexchange posts linking to pi-base

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#259]
Not really an issue for this repo, but a project to help discoverablity.

https://math.stackexchange.com/search?q=url%3A%22topology.jdabbs.com%22 shows posts that link to the old domain. Some of these redirect fine, others don't. In particular, several older references use URL params that are no longer supported for searches.

I've submitted edit requests for a handful of the first results, but hit my limit for pending edits. So this will be a slow process (but others could assist with it).

**Comment by prabau** [comment]
I started making some edits for this.  And then came across this one:
https://math.stackexchange.com/questions/4484979

where the answer from Samuel Adrian Antz links to topology.jdabbs.com and also to https://counterexamples.info.  This latter site seems completely up to date even!  Is this a link to the real one, or a pirated copy?

**Comment by StevenClontz** [comment]
> https://counterexamples.info/

Ha, I think that's just another domain James bought at some point. Next time I connect with him I'll suggest he set it up as a redirect or take it down.

**Comment by StevenClontz** [comment]
All links have now been updated.
