### ISSUE TITLE
Add open long line

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#262]
https://mathoverflow.net/questions/314611/is-every-uncountable-homogeneous-connected-t-2-space-isomorphic-to-a-subspace/314615#314615

Adds counterexample to this empty search https://topology.pi-base.org/spaces?q=First%20Countable%20%2B%20%24T_2%24%20%2B%20Connected%20%2B%20Homogeneous%2B~Second%20Countable

**Comment by prabau** [comment]
See space S153, deleted for lack of references in https://github.com/pi-base/data/commit/3d06643.

I can give it a go, unless one of you wants to work on it.

**Comment by StevenClontz** [comment]
Recreating as S153 sounds like a plan to me. I will post here if I get to it before you do; otherwise go for it.
