### ISSUE TITLE
Merge S50 into S27

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#278]
See https://math.stackexchange.com/questions/1849271/homeomorphism-between-evenly-spaced-integer-topology-and-the-rationals ~~which I'll attempt an answer to (though it follows as a corollary to the usual characterizations of the rationals)~~. (EDIT: never mind, got to be too tedious to be worth the time, but would be an interesting student question someday...)

**Comment by prabau** [comment]
Yeah, I knew about it, but tedious indeed.  Sometimes it's useful to have two perspectives on a space, especially as the homeomorphism is not explicit.

**Comment by StevenClontz** [comment]
Agreed on usefulness of perspectives, unsure if the best way to handle it is having two IDs for the same space.

**Comment by prabau** [comment]
Another example of this is https://topology.pi-base.org/spaces/S000028, which already combines counterexamples 31 and 102.

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/2328731 has some useful links for the topological characterization of $\mathbb Q$.

**Comment by StevenClontz** [comment]
https://github.com/pi-base/web/issues/134
