### ISSUE TITLE
Example of door space

### ISSUE THREAD

**Issue by prabau** [pi-base/data#295]
I think it would be good to have as an example space the one mentioned in the answer to https://math.stackexchange.com/questions/3088994/examples-of-connected-door-spaces.
It's case (3) of Theorem 1 in https://arxiv.org/abs/1809.03085 and provides another example of a space that is anticompact and not compactly generated.

What would be a good name for it?  I was thinking of something like "Ultrafilter connected door space" maybe.  It's not completely descriptive (as the particular point topology could be considered an ultrafilter space based on a principal ultrafilter), but it's good enough to distinguish it among other spaces in pi-base.  Any other suggestions?

And we could add "door space" as a property.  Not super important, but there are a few papers using that notion, so why not.

**Comment by StevenClontz** [comment]
Is this the subspace of https://topology.pi-base.org/spaces/S000111 dropping the free ultrafilter itself as a point? If so, I think they should be named similarly (and I'm not a fan of the current name for S111).

I have no problem with adding door space property as it's in the literature. Maybe "doored" as the main name as we typically use adjectives?

**Comment by StevenClontz** [comment]
Maybe S111 = "Single principal ultrafilter space" (keeping "single ultrafilter topology" as an alias) and Snew = "Single principal ultrafilter subspace" as main names?

**Comment by prabau** [comment]
S111 without the ultrafilter point is discrete, so it's very different.

We usually use adjectives for properties, but I think "door space" sounds much better than "doored".  It is consistently used in the literature for such spaces.  And pi-base has some other properties with the word "space" in them, like $G_\delta$ space, spectral space, q space, k space, M space, etc.

Talking about adjectival forms of properties, we also have "groupable", which sounds pretty horrible to me, but that would be another discussion.

**Comment by prabau** [comment]
Or, following the description of P87, "homeomorphic to topological group" maybe. (would that be too long?) Maybe we can brainstorm in the meeting today.

**Comment by prabau** [comment]
Still looking for a good name.  Any suggestions?

**Comment by StevenClontz** [comment]
Maybe S111 could be renamed "Single ultrafilter subspace of $\beta\omega$"?

And maybe this is "Free ultrafilter topology on $\omega$"? To distinguish from a particular point topology induced by a principal ultrafilter.

**Comment by StevenClontz** [comment]
What search would this space answer that's doesn't already have an example in pi-Base?

**Comment by prabau** [comment]
I like your name suggestions, in particular the one for S111.

One search that the new space would fulfill: [π-Base, Search for `door+connected+T1+multiple points`](https://topology.pi-base.org/spaces?q=door%2Bconnected%2BT1%2Bmultiple+point)

**Comment by StevenClontz** [comment]
🤦 I should have clocked that all the other connected door spaces weren't T1. Thanks! :-)
