### ISSUE TITLE
Example of Totally Separated Λ Metrizable Λ ¬Zero Dimensional

### ISSUE THREAD

**Issue by Claudio-Agostini** [pi-base/data#315]
At the moment, the website does not provide an example of Totally Separated, Metrizable space which is not Zero Dimensional.

An example of such a space can be found here: https://math.stackexchange.com/questions/2866455/difference-between-zero-dimensional-and-totally-separated-in-the-plane

**Comment by StevenClontz** [comment]
Here's the search that currently returns no results: https://topology.pi-base.org/spaces?q=Totally%20Separated%2BMetrizable%2B~Zero%20Dimensional

**Comment by StevenClontz** [comment]
I see two relevant examples we might add.

- "Sierpiński's E-space": Separable Λ Metrizable Λ Totally Separated Λ ¬Zero Dimensional
- "Sierpiński's E1-space": Separable Λ Metrizable Λ Totally Disconnected Λ ¬Totally Separated (another space with these props: https://topology.pi-base.org/spaces/S000126 )

**Comment by prabau** [comment]
Erdős space (#633) now provides one example.

**Comment by prabau** [comment]
#633 has been marked as closing #315.  Does that mean that, unless someone volunteers, we won't add Sierpinski's E and E1 spaces for now?

**Comment by StevenClontz** [comment]
We can keep this issue open if you want, but the title should be updated. Do these spaces answer any other interesting questions that your example in #633 doesn't?

**Comment by prabau** [comment]
Personally, I am ok with closing this issue.  I am not too familiar with the spaces E and E1, but I think the Erdos space is nicer and easier to work with.  It's also defined in a very natural way, as opposed to Sierpinski's ad hoc examples.  But I wanted the decision to not add E and E1 at the moment to be made explicit here, so the author of this issue at least knows why.
