### ISSUE TITLE
Selection principles; Fortissimo spaces

### ISSUE THREAD

**Issue by ccaruvana** [pi-base/data#327]
I have been wanting to make some additions to the pi-base to elaborate on selection principles, but I wanted to ask for input before formulating a pull request.

As stated in the Dover edition of Counterexamples, example #25 is a class of examples since it doesn't specify cardinality. So the Fortissimo topology on $\omega_1$ is not generally https://topology.pi-base.org/spaces/S000022 and has some properties that Fortissimo on the reals won't have in models of not CH. To add Fortissimo on $\omega_1$, can the descriptor be "an instance of #25 from Counterexamples" and maybe update the language for space 22 as well to reflect that it is an example of type #25?

For the selection principles part of this issue, I plan on adding some other properties that appear in the literature like epsilon-space and k-Rothberger. Should I also update https://topology.pi-base.org/properties/P000069 with a description of the Menger game itself, or perhaps include a reference to the linked paper where the Menger game is discussed?

**Comment by prabau** [comment]
Your suggestion to mention that S22 and your new example are specific instance of counterexample #25 makes sense to me.

Leaving it up to others to comment on the selection principles part, but just for my own edification: In the case of not-CH, the two spaces will be different.  Will there be old or new properties or their negation than can then be asserted for one and not the other, or is it still undetermined, based on what the value of the continuum is?  (Another option would be to replace the reals with $\omega_1$ in S22, not sure if it's better or not.)

**Comment by ccaruvana** [comment]
That's a great question. I guess it would be worthwhile to take a look through the asserted properties for S22 to see the cardinality of the reals comes in to play at all.

As for a particular topological difference, I can see how probably the weight of the space will change depending on the cardinality of the "ground" set. For example, I would imagine it's true that the Fortissimo space on a cardinal $\kappa$ has weight $\kappa$, but that won't be reflected in any of the properties the pi-base currently has. The only property that sticks out is "continuum-sized," which has the obvious problem in this context.

**Comment by prabau** [comment]
Yes, some of the cardinality properties will change in the obvious way.  I don't think anything else currently would (especially since under CH they would be the same space).  But I was asking more whether there would be a difference for the Menger and other selection principles based properties.

**Comment by ccaruvana** [comment]
At any rate, I now think it sensible to leave S22 as is and not introduce Fortissimo on $\omega_1$ into the pi-base just yet. With that said, I'll tentatively start working on a pull request.

**Comment by ccaruvana** [comment]
As an update to the original post, I followed the example set by https://topology.pi-base.org/properties/P000069 since a description of the corresponding game and defining strategy types is bulky. However, perhaps we can be more direct for the user by including the reference in the description of the property (instead of leaving them to click on the references tag and then navigate to the linked article). For example, after the definition of P69, we could include "See {referenced link} for more details."

**Comment by prabau** [comment]
Yeah, I agree that's a case where the description of the property is too bulky.  Adding your suggestion for P69 would be helpful for users, I think.

**Comment by ccaruvana** [comment]
With that change, I feel like this issue is near closing. From this point, I think it's worth leaving open until Steven can provide any input, if/whenever he wants. I will plan to add the corresponding properties with respect to $k$-covers in the near future.

**Comment by ccaruvana** [comment]
Closing this for now. As mentioned in https://github.com/pi-base/data/pull/329, we'll air out the Fortissimo space stuff a bit more on math.se.
