### ISSUE TITLE
Adding an example of a scattered Tychonoff non-zero-dimensional space

### ISSUE THREAD

**Issue by Claudio-Agostini** [pi-base/data#363]
At the moment, there is no example of scattered Tychonoff non-zero-dimensional space. Here is the query that provides no results: https://topology.pi-base.org/spaces?q=Scattered%20%2B%20~zero%20dimensional%20%2B%20%24T_%7B3%20%5Cfrac%7B1%7D%7B2%7D%7D%24

An example of such a space is described for example in a paper by Solomon, "A Scattered Space that is not Zero-Dimensional", Bulletin of the London Mathematical Society, Volume 8, Issue 3, November 1976, Pages 239–240, https://doi.org/10.1112/blms/8.3.239
Here is a link to the paper: https://academic.oup.com/blms/article-abstract/8/3/239/323158?redirectedFrom=fulltext&login=false

**Comment by StevenClontz** [comment]
Thanks for the reference for this missing result.
