### ISSUE TITLE
The name "Completely Hausdorff" is confusing

### ISSUE THREAD

**Issue by prabau** [pi-base/data#382]
I always find the name "completely Hausdorff" confusing.  It is used as the primary name for https://topology.pi-base.org/properties/P000009  (P9 = distinct points can be separated by continuous functions).  It's also an alias for https://topology.pi-base.org/properties/P000004, with T2.5 for the main name.  (P4 = distinct points can be separated by closed neighborhoods)

(see https://en.wikipedia.org/wiki/Separated_sets and https://en.wikipedia.org/wiki/Urysohn_and_completely_Hausdorff_spaces)

"Completely Hausdorff" means P9 in Willard and means P4 in Steen & Seebach.  Means different things in different sources.  I did not see either of these notions in Engelking.
(the term "Urysohn" is also confusing as it is used differently in different sources, and shows up as in alias in multiple pi-base properties, but it's not a primary name, so ignoring this here).

On the other hand, P9 also has the alias "functionally Hausdorff", which seems pretty descriptive to me, with no possible ambiguity.  Also note that Willard defines "completely Hausdorff" in 14G and gives "functionally Hausdorff" as a synonym.

What would you guys think of the idea of making "functionally Hausdorff" the primary name for P9?

**Comment by StevenClontz** [comment]
I've had the same thought actually: functionally Hausdorff is much less ambiguous.
