### ISSUE TITLE
Spaces where all convergent sequences are eventually constant

### ISSUE THREAD

**Issue by prabau** [pi-base/data#387]
Spaces where all convergent sequences are eventually constant keep appearing in various arguments.  I think it would be useful to add this as a property in pi-base.

I have asked https://mathoverflow.net/questions/451796/topological-property-of-convergent-sequences-being-eventually-constant to see if there is a usual terminology for this.

What do you think?

**Comment by Moniker1998** [comment]
According to Encyclopedia of General Topology by Hart, Nagata, Vaughan, extremally disconnected spaces have this property. 
They claim it for Tychonoff spaces but this can probably be weakened. 

I believe this property also implies some weak separation properties.

**Comment by prabau** [comment]
As mentioned in Steven Clontz's answer to https://math.stackexchange.com/questions/4744697, T1 P-spaces should also have that property.

And the property at least implies US, which implies T1.

**Comment by Moniker1998** [comment]
I think that if we're going to add this property to pi-base, we should call such spaces sequentially discrete.

Not only would it propagate a good name for it, but there also don't seem to be any other names out there.

We could put "No non-trivial sequences" as an alias in case someone doesn't know that such spaces are called sequentially closed.

**Comment by StevenClontz** [comment]
I'm working a bit here: https://math.stackexchange.com/questions/4751580/are-all-extremally-disconnected-spaces-sequentially-discrete

Here's one result: Consider a strongly KC space. Every sequence is countably compact, and therefore closed. It follows that every convergent sequence must eventually be constant.

A conjecture: in extremally disconnected spaces, strongly KC, sequentially discrete, and US are all equivalent (and thus also KC and Weak Hausdorff).
