### ISSUE TITLE
A metrizable meager space of size continuum

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#388]
A space like in the title currently doesn't exist in pi-base. 
It'd be useful to prove or refute the theorem [metrizable + not size < continuum => not meager]

**Comment by Moniker1998** [comment]
I found an example here https://math.stackexchange.com/questions/3198478/topological-spaces-meager-in-itself
Such metric space exists for any infinite cardinal $\kappa$, just take coproduct of $\kappa$ copies of $\mathbb{Q}$

**Comment by Moniker1998** [comment]
Perhaps it would be nice to have $\bigsqcup_{i\in\mathbb{R}} \mathbb{Q}$ included to pi-base?

**Comment by prabau** [comment]
Handled in #393
