### ISSUE TITLE
Tychonoff corkscrew

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#396]
I believe that a lot of properties of the Tychonoff corkscrew were not included in pi-base?

For example it seems to be a space which is not countably compact and not countably paracompact, since it contains a closed copy of the deleted Tychonoff plank. (this was listed as *it is* countably compact and countably paracompact in Counterexamples in topology by Steen and Seebach (seems wrong?)).

It's also not listed as completely regular, while this is it's main property as a counter-example.

**Comment by prabau** [comment]
See #476

**Comment by prabau** [comment]
See also https://math.stackexchange.com/questions/4819068/paracompactness-properties-of-the-deleted-tychonoff-plank.
I'll make a few more tweaks after getting an answer.

**Comment by prabau** [comment]
Closed by #476.
