### ISSUE TITLE
Specific reference for P166: 10.1007/BFb0098389

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#403]
Assuming #402 is merged, P166 references a book, but we should point to the specific desired result that among T_{3.5} spaces, having a coarser separable metrizable topology is equivalent to Cp(X) being separable.

**Comment by StevenClontz** [comment]
According to https://prometeo2013058.blogs.upv.es/files/2015/12/18-sc-Cap-4-libro.pdf the result is on page 54.

**Comment by prabau** [comment]
It seems this was implemented in #408 and is now completed.
