### ISSUE TITLE
t1-not-t2 counterexamples

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#428]
Making a checklist of all the T1-to-T2 theorems and counterexamples of late; stuff that's missing can go in a future PR:

### kH/KC/wH/US

- [x] [T2 -> k1H](https://topology.pi-base.org/theorems/T000228)
    - [x] [counterexample to converse](https://topology.pi-base.org/spaces/S000017)
- [x] [k1H -> KC](https://topology.pi-base.org/theorems/T000424)
    - [x] several counterexamples
- [x] [KC -> wH](https://topology.pi-base.org/theorems/T000227)
    - [x] [counterexample to converse](https://topology.pi-base.org/spaces/S000031) 
- [x] wH -> k2H
    - [x] [counterexample to converse](https://topology.pi-base.org/spaces/S000165)
- [x] k2H -> US
    - [x] [counterexample to converse](https://topology.pi-base.org/spaces/S000037)
- [x] [US -> T1](https://topology.pi-base.org/theorems/T000226)
    - [x] lots of counterexamples

### RC

- [x] [T2 -> RC](https://topology.pi-base.org/theorems/T000310)
    - [x] several counterexamples
- [x] [RC -> T1](https://topology.pi-base.org/theorems/T000311)
    - [x] lots of counterexamples

### sH

- [x] [T2 -> sH](https://topology.pi-base.org/theorems/T000420)
    - [x] several counterexamples
- [x] [sH -> T1](https://topology.pi-base.org/theorems/T000419)
    - [x] lots of counterexamples

### lH

- [x] [T2 -> lH](https://topology.pi-base.org/theorems/T000193)
    - [x] several counterexamples
- [x] [lH -> T1](https://topology.pi-base.org/theorems/T000195)
    - [x] two counterexamples

### cross-incompatibility

- [x] [k1H not RC](https://topology.pi-base.org/spaces?q=k-Hausdorff%2B~Retracts%20are%20closed)
- [x] [k1H not sH](https://topology.pi-base.org/spaces?q=k-Hausdorff%2B~Semi-Hausdorff)
- [x] [k1H not lH](https://topology.pi-base.org/spaces?q=k-Hausdorff%2B~Locally%20Hausdorff)
- [ ] RC not US - this has not appeared in the literature or in explicit detail onlne - will require digging into the example at https://mathoverflow.net/a/435973/73785 (could add RC not KC for now). For what it's worth, I believe the result is correct, but it's quite intricate. On the other hand, my attempts to build a less elaborate example have fallenshort.
- [x] [RC not sH](https://topology.pi-base.org/spaces?q=Retracts%20are%20closed%2B~Semi-Hausdorff)
- [x] [RC not lH](https://topology.pi-base.org/spaces?q=Retracts%20are%20closed%2B~Locally%20Hausdorff)
- [x] [sH not US](https://topology.pi-base.org/spaces?q=Semi-Hausdorff%2B~US)
- [x] [sH not RC](https://topology.pi-base.org/spaces?q=Semi-Hausdorff%2B~Retracts%20are%20closed)
- [x] [sH not lH](https://topology.pi-base.org/spaces?q=Semi-Hausdorff%2B~Locally%20Hausdorff)
- [x] [lH not US](https://topology.pi-base.org/spaces?q=Locally%20Hausdorff%2B~US)
- [x] [lH not RC](https://topology.pi-base.org/spaces?q=Locally%20Hausdorff%2B~Retracts%20are%20closed)
- [x] [lH not sH](https://topology.pi-base.org/spaces?q=Locally%20Hausdorff%2B~Semi-Hausdorff)

**Comment by danflapjax** [comment]
RC and not US is satisfied by [S192](https://topology.pi-base.org/spaces/S000192).
