### ISSUE TITLE
Double origin topology T2 proof inequality is wrong (I am pretty sure)

### ISSUE THREAD

**Issue by chadnash** [pi-base/data#441]
https://topology.pi-base.org/spaces/S000066/properties/P000003 
In the definition of V should  the inequality 
    x ^2 +y ^2 >1 
be 
   x ^2 +y ^2 < 1

**Comment by chadnash** [comment]
I think now I m wrong sorry

**Comment by chadnash** [comment]
now I think I am right and for V it should also be  y<0

**Comment by prabau** [comment]
Thanks for letting us know.  Also the formatting is messed up.  We'll fix this.
