### ISSUE TITLE
Dieudonné plank definition

### ISSUE THREAD

**Issue by prabau** [pi-base/data#462]
I was looking at the Dieudonné plank and there seems to be a discrepancy between Steen & Seebach and pi-base.

For background, there is the Tychonoff plank and the deleted Tychonoff plank.  Each of them illustrates different sets of properties.  The Dieudonné plank is basically the Tychonoff plank with a finer topology, i.e. the product $(\omega_1+1)\times(\omega+1)$ where the $\omega_1+1$ factor has a finer topology than the usual order topology.  And in parallel to the Tychonoff versions, one can define a Dieudonné plank and a deleted Dieudonné plank, each illustrating different sets of properties.

Now S&S calls "Dieudonné plank" the deleted version.  And pi-base calls "Dieudonné plank" the full version with the corner point $(\omega_1,\omega)$.  It would be good if S&S and pi-base were using the same terminology.  But maybe more importantly, it would be good to have both versions in pi-base, even if it does not match S&S exactly.

Any thoughts on this?

**Comment by StevenClontz** [comment]
I'll make a strawman PR with my pitch.

**Comment by StevenClontz** [comment]
See #463, which needs to be fleshed out with properties of the non-deleted plank.
