### ISSUE TITLE
Single point space

### ISSUE THREAD

**Issue by tomaszrz1** [pi-base/data#49]
It seems like the one-point space is a counterexample to some otherwise obvious implications (e.g. https://topology.jdabbs.com/theorems/I000088 says that a path connected space is not totally path disconnected, but the one-point space is both) due to vacuous quantification over pairs.

Excluding empty set as a topological space is acceptable for most math, but I don't think we can say the same about the one-point space.

I suggest adding the one-point space to the database, along with the property of having more than one point. I'm not sure whether it is better to assert the properties of the one-point space, or to add theorems deducing various properties from one-pointedness.

**Comment by StevenClontz** [comment]
Yep, this doesn't surprise me. Our solution was to add the trivial/indiscrete property: https://github.com/pi-base/data/blob/master/properties/P100052.md

You are correct that a one-point space should be added if it's not already in there. It would be the unique space which is both trivial and discrete. Right now https://topology.pi-base.org/ is having server issues so it's hard for me to conveniently look things up but I'll look into this and your PR in August.
