### ISSUE TITLE
S133 clean-up

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#504]
It was asked at https://math.stackexchange.com/questions/4833751 if a certain space was in the $\pi$-Base. As it turns out, yes, it is, but it wasn't obvious due to the very specified construction. It'd be good to make this clearer in the $\pi$-Base, and while we're at it, remove some of the redundant assertions.

I've invited the asker of https://math.stackexchange.com/questions/4833751 to make this contribution, so they are encouraged to reply here to learn more.

**Comment by gregorynisbet-google** [comment]
Hello all,

I'm Greg Nisbet, the author of the linked question. I'd be more than happy to update the files.

I would like some direction on exactly what to change, if that's all right.

I'd also like to know if there are any instructions for how to build the project locally.  [This page](https://github.com/pi-base/data/blob/main/spaces/S000133/README.md) has some embedded LaTeX and I can probably get Emacs to render it inline, but I'm curious if there's a preferred way to do that.

Thanks,
Greg

**Comment by gregorynisbet-google** [comment]
I started work on https://github.com/pi-base/data/pull/506 . It is not finished. I'll work on it some more and remove the `[DO NOT MERGE]` label from the title when it is ready for review.

I still need to look around some more to see how to do citations (and some other stuff).

**Comment by gregorynisbet-google** [comment]
I made my PR ready for review. From what I can gather, citations to math exchange are just done as markdown links `[example](like this)`, aside from `{{mathse:question#}}` links which also exist.

**Comment by StevenClontz** [comment]
Thanks - sorry for my slow reply! I've made a suggested tweak in #516 - feel free to comment there, here, or in #506. Thanks for your time. :-D

**Comment by prabau** [comment]
#516 completed this.
