### ISSUE TITLE
Theorem Suggestion: Include theorems for deducing and upgrading $k$-space properties when locally Hausdorff

### ISSUE THREAD

**Issue by marswill** [pi-base/data#523]
---

## Changes
**New Theorem 1.** ($\text{locally Hausdorff} + \text{locally compact} \implies CG3$.) If a space is:

- [P84](https://topology.pi-base.org/properties/P000084)
- [P130](https://topology.pi-base.org/properties/P000130)

then it is [P142](https://topology.pi-base.org/properties/P000142).

---

**New Theorem 2.** ($\text{locally Hausdorff} +CG2 \implies CG3$.) If a space is:

- [P84](https://topology.pi-base.org/properties/P000084)
- [P141](https://topology.pi-base.org/properties/P000141)

then it is [P142](https://topology.pi-base.org/properties/P000142).

----

**Property Addition.**  (One point compactification of Arens-Fort space is locally Hausdorff).  Space [S165](https://topology.pi-base.org/spaces/S000165) has property [P84](https://topology.pi-base.org/properties/P000084)

-----

## Rationale

Looking at [T309](https://topology.pi-base.org/theorems/T000069), ($CGWH \implies CG3$), I was astonished to see there were no counterexamples to the converse, given the many variations on the telophase topology we have.

It seems none of these have $CG3$ deduced.

We could deduce most of these automatically via the first of the preceding theorems, and pick up the non-locally compact stragglers like [S97](https://topology.pi-base.org/spaces/S97) with the second.  (Technically we could probably get all with just the second theorem, but the first seems important and can't be deduced from the second).

Finally, adding local Hausdorff to the Arens Fort space is worth doing for its own sake, but also beneficial as it shows why we can't simply relax Hausdorff to local Hausdorff in [T60](https://topology.pi-base.org/theorems/T000060).

------

## Proof/References

These are all pretty straightforward.  

For Theorem 1, Local Hausdorff and locally compact gives a base of compact Hausdorff spaces, which therefore generate the topology.  

For Theorem 2, If $X$ is CG2 and locally Hausdorff and $A\subseteq X$ is not closed, then by CG2 we have a map $f\colon Z\to X$ from compact Hausdorff $Z$ with $f^{-1}(A)$ not closed.  Let $z\in \overline{f^{-1}(A)}\backslash f^{-1}(A)$, let $U\ni f(z)$ be a Hausdorff open neighborhood, and choose a neighborhood $V$ of $z$ with $\overline{V}\subseteq f^{-1}(U)$, then $f(\overline{V})$ is compact Hausdorff.  Since $z\in \overline{f^{-1}(A)\cap \overline{V}}\backslash f^{-1}(A)$, $f(z)\in \overline{A\cap f(\overline{V})}\backslash A$, so $f(\overline{V})\subseteq U$ is compact Hausdorff, with $f(\overline{V})\cap A$ not closed in $f(\overline{V})$.

Finally, the one point-compactification $X\^\*$ of the Arens-Fort space $X$ is locally Hausdorff, since $X$ is Hausdorff, and $\infty$ has $X\^\*\backslash\\{(0,0)\\}$ as a Hausdorff neighborhood (note this neighborhood is homeomorphic to $\omega+1$).

------

If it's alright I'm going to assign this one to myself so I can go through all the steps and get a little more familiar with pi-base in general.

**Comment by marswill** [comment]
Hmm, are these arguments short enough to directly paste in without making a Math.SE post to reference?  I feel like for Theorem 1 and the new Property it should be fine, but is Theorem 2 pushing it too far?  @StevenClontz  @prabau I'd be grateful for either of your thoughts.

**Comment by prabau** [comment]
I haven't looked yet at the details of your proposal (will look tomorrow).  But as a general principle for pi-base, as Steven told us, pi-base is in the business of reflecting peer-reviewed mathematics rather than reviewing suggested contributions.  And generally results should be accompanied by some reference ("refs" field).  The previous reviewing may mean having appeared in a mathematics journal/book, but also just having stood scrutiny on mathse or mo.  At the same time if a result is really simple or just a few lines of argument, we have decided it's acceptable to have it in pi-base without refs.  It's really a judgment call.

**Comment by marswill** [comment]
@prabau 

Thanks, based on your comment and doing some more thinking on this, I think I'll just go ahead and ask/answer on Math.SE.
