### ISSUE TITLE
Tighten up theorem T10

### ISSUE THREAD

**Issue by marswill** [pi-base/data#533]
*Modify the below template for your theorem suggestion:*

## Modify Theorem [T10](https://topology.pi-base.org/theorems/T000010) 

to say that if a space is:

- [P49](https://topology.pi-base.org/properties/P000049) (extremally disconnected)
- [P84](https://topology.pi-base.org/properties/P000084) (locally Hausdorff)

then it is [P167](https://topology.pi-base.org/properties/P000167) (sequentially discrete).

## Rationale

The current version, which says [P53](https://topology.pi-base.org/properties/P000053) (metrizable) and [P49](https://topology.pi-base.org/properties/P000049) (extremally disconnected) implies [P52](https://topology.pi-base.org/properties/P000052) (discrete), would be recoverable, since we have [T416](https://topology.pi-base.org/theorems/T000416) (sequential and sequentially discrete imply discrete).

In any case, the current proof appears incorrect so some modification needs to be done anyway.  

The new proof will allow discovery of $\neg(\text{extremally disconnected})$ on nonmetrizable spaces such as the recently added [S131](https://topology.pi-base.org/spaces/S000131) (Sequential fan with $\omega$-many splines.)

## Proof/References

The result is given by Ulli's answer to this question [this Math.StackExchange post](https://math.stackexchange.com/q/4751580/1210477).  While stated for Hausdorff spaces, the proof immediately applies to locally Hausdorff spaces by restricting to a Hausdorff neighborhood of the limit point.

**Comment by prabau** [comment]
This change is good.  I had noticed also that the previous proof for T10 was not correct.

**Comment by prabau** [comment]
General comment to simplify the workflow.  If a change is uncontroversial and does not require extensive discussion, feel free to open a PR directly without having a corresponding issue.  The details of the rationale for it can be explained in comments in the PR itself.
