### ISSUE TITLE
S24 description needs clarification.

### ISSUE THREAD

**Issue by marswill** [pi-base/data#544]
[S24](https://topology.pi-base.org/spaces/S000024) ("Modified Fort Space on the Real Numbers") seems to need clarification.  Right now it says 

>Let $X = \mathbb R\cup \\{\infty_1,\infty_2\\}$.  Define $U\subset X$ to open if its complement is finite or includes either $\infty_1$ or $\infty_2$.  

This does not define a topology, as $\\{\infty_1\\}$ and $\\{\infty_2\\}$ would be open and not $\\{\infty_1,\infty_2\\}$.
 
I am inferring from the properties that it should read

>Let $X = \mathbb R\cup \\{\infty_1,\infty_2\\}$.  Define $U\subset X$ to open if its complement is finite or includes ***both*** $\infty_1$ and $\infty_2$.  

However, don't want to fix this myself since I don't have a copy of Steen/Seebach to confirm this.

**Comment by prabau** [comment]
Yeah, the description for S24 does not make much sense to me either. Steen & Seebach has the following:
> Let the set $X$ be the union of any infinite set $N$ and two distinct one point sets $\\{x_1\\}$ and $\\{x_2\\}$.  We topologize $X$ by calling any subset of $N$ open and calling any set containing $x_1$ or $x_2$ open iff it contains all but a finite number of points in $N$.

So I think it would be clearer to say something along the lines of:
> Every point of $\mathbb R$ is isolated and the open neighborhoods of each point $\infty_i$ are the cofinite subsets of $X$ containing the point.

What do you think?

**Comment by marswill** [comment]
> What do you think?

That seems nice and clear, I like it.
