### ISSUE TITLE
New property: embeddable in Euclidean space

### ISSUE THREAD

**Issue by prabau** [pi-base/data#565]
As @StevenClontz had suggested a while ago, it would be useful to add "embeddable in Euclidean space" as a property.

The description would be something like this:
> The space can be embedded as a subspace of some Euclidean space $\mathbb R^n$ for some integer $n$.

In addition to the interest in the property itself, it would also facilitate data entry and automatic deduction of other properties.

My only doubt is about the best name for this:
- "Embeddable in Euclidean space"
- "Embedded in Euclidean space" (a slight misnomer, but shorter and easier?)
- "Embeds into Euclidean space"
- something else?

Comments?

**Comment by marswill** [comment]
Seems reasonable.  Right now it seems like it automatically deduces second countable and metrizable.  At some point we probably add one or more various definitions of finite dimensionality to pi base, and then embeddable in Euclidean space becomes equivalent to second countable + metrizable +finite dimensional, but it will still remain a nice convenience property.

What about "Embeds into Euclidean space"?

**Comment by prabau** [comment]
@StevenClontz I could not find the previous discussion in Issues, but finally found it in under Discussions at #324.

**Comment by prabau** [comment]
> embeddable in Euclidean space becomes equivalent to second countable + metrizable +finite dimensional,

Surely a well-known theorem (which I am ignorant of). Do you have any reference?

**Comment by prabau** [comment]
> What about "Embeds into Euclidean space"?

I updated the list of possibilities at the top.  Hope the others chime in.

**Comment by marswill** [comment]
> > embeddable in Euclidean space becomes equivalent to second countable + metrizable +finite dimensional,
> 
> Surely a well-known theorem (which I am ignorant of). Do you have any reference?

 I believe I first saw it in Hurewicz and Wallman's book, but don't have that available at the moment.  In any case it is in *Dimension Theory* by Engelking, Theorem 1.11.4 (p. 120).  The book is online at https://www.maths.ed.ac.uk/~v1ranick/papers/engelking.pdf

**Comment by danflapjax** [comment]
I do like "Embeds into Euclidean space", although "Euclidean subspace" seems like another reasonable option.

Regarding the theorem that it's equivalent to second countable + metrizable + finite-dimensional, I notice that multiple existing properties imply finite dimensional, including [zero dimensional](https://topology.pi-base.org/properties/P000050), [LOTS](https://topology.pi-base.org/properties/P000133), and [locally n-Euclidean](https://topology.pi-base.org/properties/P000123). I personally would prefer to add a finite-dimensional property now to be cleanly deduced from all these properties rather than kick the can down the road.

**Comment by marswill** [comment]
> I do like "Embeds into Euclidean space", although "Euclidean subspace" seems like another reasonable option.

It's reasonable, but a slight misnomer again, since a space that embeds into another need not actually be a subspace.  Potentially some of the examples in pi base will not actually be defined as Euclidean sub spaces, e.g., I forget if we do it this way currently but $\omega+1$ is an example of this.

**Comment by danflapjax** [comment]
> In any case locally Euclidean under any of the three definitions without regularity or normality will not imply finite dimensional - line with infinitely many origins would be infinite dimensional for all three definitions.

Oh, great point. I had thought through how the other two properties related to Engelking's definition of covering dimension but only considered locally Euclidean in conjunction with the second countable and metrizable assumptions.

> There's lots of interesting stuff here, and we could certainly add dimension(s) sooner rather than later, though I'm not sure we need to do it before "embeds into Euclidean Space". Are there particular things we would need to undo and redo differently if we do Embeds into Euclidean first without dimension?

My only thought was that having multiple very similar theorems to derive Euclidean embeddings when there exists another underlying property to unify them would be wasted effort in the long run. Having three or so different theorems is certainly not the end of the world, though, and it's clear that questions regarding dimension do not have trivial answers.

**Comment by prabau** [comment]
Regarding the name, a while ago the pi-base reviewers discussed naming in general and came up with the general guideline that we prefer a name or phrase in adjectival form where possible.  That reads better when stringing together various properties in text.  And also with the new syntax to link to a specific trait of a space, something like `{S26|P200}` would expand to "_Cantor space is Embeds into Euclidean space_", which does not sounds that good.

@StevenClontz Can you comment?

**Comment by marswill** [comment]
> Regarding the name, a while ago the pi-base reviewers discussed naming in general and came up with the general guideline that we prefer a name or phrase in adjectival form where possible.  That reads better when stringing together various properties in text.  And also with the new syntax to link to a specific trait of a space, something like `{S26|P200}` would expand to "_Cantor space is Embeds into Euclidean space_", which does not sounds that good.

Hadn't considered that at all, based on that, I honestly think "embeddable in Euclidean space" is fine and doesn't really seem too clunky to me at all.

(or "embeddable *in* Euclidean space", I like "into" a little better as I think of embedding as a more active process, but don't have strong preference.)

**Comment by StevenClontz** [comment]
> Regarding the name, a while ago the pi-base reviewers discussed naming in general and came up with the general guideline that we prefer a name or phrase in adjectival form where possible. That reads better when stringing together various properties in text. And also with the new syntax to link to a specific trait of a space, something like `{S26|P200}` would expand to "_Cantor space is Embeds into Euclidean space_", which does not sounds that good.
> 
> @StevenClontz Can you comment?

Yeah, generally our property names should be adjectives for the reasons described. "Embeddable in/into/within Euclidean space" sounds best to me, and the PR creator can choose their favorite preposition out of those as far as I'm concerned.

**Comment by prabau** [comment]
@danflapjax Assigning to you as you expressed an interest.
