### ISSUE TITLE
Proposed property: partition topology

### ISSUE THREAD

**Issue by prabau** [pi-base/data#574]
I think "partition topology" would be worth adding as a property (Steen & Seebach example 5).

Not a very important property, but it has some visual appeal and has some relationships with other properties.  See for example:
- https://math.stackexchange.com/questions/4871848/is-every-regular-alexandrov-topology-a-partition-topology
- https://math.stackexchange.com/questions/4097094/what-is-the-name-for-a-topological-space-whose-kolmogorov-quotient-is-discrete

This would also allow to deduce traits for some existing spaces like [S5](https://topology.pi-base.org/spaces/S000005), [S6](https://topology.pi-base.org/spaces/S000006), and consolidate theorems for discrete and indiscrete.

@StevenClontz, @danflapjax and others, what do you think?

**Comment by danflapjax** [comment]
I think that's a great idea. Besides having a partition as a basis, a nice characterization of the property is that a set is open iff it is closed. As a result, this would complete the set of what I see as the simplest topological properties (at least in the interior algebra): the universally quantified statements relating sets to their interiors and closures. For each of the 15 not constantly true boolean functions of $U=\text{in } U$ and $U=\text{cl } U$:

| Property | $\forall U\subseteq X, U\ne \varnothing, U\ne X$ |
|-|-|
| [Empty](https://topology.pi-base.org/properties/P000137) | $\bot$|
| [Discrete](https://topology.pi-base.org/properties/P000052) | $U=\text{in } U$ <br> $U=\text{cl } U$ <br> $U=\text{in } U \wedge U=\text{cl } U$|
| [Indiscrete](https://topology.pi-base.org/properties/P000129) | $U\ne\text{in } U$ <br> $U\ne\text{cl } U$ <br> $U\ne\text{in } U \wedge U\ne\text{cl } U$ |
| [Door](https://topology.pi-base.org/properties/P000126) | $U=\text{in } U \vee U=\text{cl } U$ |
| [Connected](https://topology.pi-base.org/properties/P000036) | $U\ne\text{in } U \vee U\ne\text{cl } U$ | 
| Door and Connected | $U=\text{in } U \veebar U=\text{cl } U$ |
| Partition | $U=\text{in } U \Rightarrow U=\text{cl } U$ <br> $U=\text{in } U \Leftarrow U=\text{cl } U$ <br>  $U=\text{in } U \Leftrightarrow U=\text{cl } U$  |

**Comment by prabau** [comment]
@danflapjax Cool.  Let's see if @StevenClontz is also ok with the idea.  And if so, would you be interested in working on this as your time allows, since you recently submitted a PR for improving S6?  If so, we'll assign this issue to you.

**Comment by StevenClontz** [comment]
Cool with me. 👍

**Comment by danflapjax** [comment]
@prabau Yeah, I'd be interested in contributing this (as time allows, as you say)

**Comment by prabau** [comment]
Thank you.  No rush
