### ISSUE TITLE
scrub unused UIDs from traits

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#58]
As noted in #56 we don't use them anymore, but they still appear in the repo (and might cause confusion). So unless we need them for legacy reasons we should remove them.

**Comment by StevenClontz** [comment]
@jamesdabbs can you think of any reason we need to keep UIDs on space/property pairs? They don't seem to be used anymore.

**Comment by jamesdabbs** [comment]
"Not breaking old bookmarks" is the only reason I can think of. At _some_
point we had a URL compatibility layer that would redirect `traits/T...`
from an old routing scheme to `spaces/.../properties/...`. I'm not entirely
sure if that's in the current version. If not, I'm all for trimming this.
If it _is_, I'm less sure. We could try to capture some analytics, but it
may just not be worth the trouble.

**Comment by StevenClontz** [comment]
I didn't check the viewer source, but I did try variations on `/T000001` and `/traits/T00001` on topology.pi-base.org and didn't seem to get anything but 404s. So it sounds like running a search on `/spaces/*/properties/*` and removing any `uid:` lines is reasonable.

**Comment by prabau** [comment]
@StevenClontz The work is now done.  You can close the issue.
