### ISSUE TITLE
New property: Continuum

### ISSUE THREAD

**Issue by prabau** [pi-base/data#612]
The pi-base homepage https://topology.pi-base.org/ has "non-metric continua" as an example for searching spaces by properties.  Yet pi-base doesn't know what a continuum is and behind the scenes that search is manually tweaked to make things work.  If we had that property, the sample search could be simplified accordingly.

And since it's a common notion, it also seems worth adding if only to make the terminology available.  Both Willard and Engelking define a **continuum** as a compact connected Hausdorff space.

**Comment by Moniker1998** [comment]
The most common definition of continuum seems to be a *metrizable* compact connected space.

This is true for most canonical texts about continuum theory, for example see Continuum theory by Nadler.

**Comment by StevenClontz** [comment]
Definitely depends on your circle of research - at the conferences I frequent, folks usually qualify "metrizable continuum" vs "Hausdorff continuum" or "non-metrizable continuum" to disambiguate. (There's a reason that James had non-metric continua as a ready example when he created that jumbotron years ago!)

The $\pi$-Base typically errs on the side of less assumptions, but perhaps naming the property "Hausdorff continuum" would be best.

**Comment by prabau** [comment]
As for "Hausdorff continuum", that does not seem necessary to me.  We can assume all the continua we consider are always Hausdorff (which is certainly the case for metric continua).

Or are you suggesting to have continuum = compact + connected without Hausdorff?  Some papers just say that, but then they seem to make the implicit blanket assumption that all their spaces are Hausdorff anyway.

**Comment by StevenClontz** [comment]
I'm suggesting Hausdorff continuum since I hear it used to emphasize when a speaker is not assuming continua are necessarily metrizable.

**Comment by Moniker1998** [comment]
Its not a matter of assuming the least amount of conditions as possible, is how I see it. 

Its just that metrizable and Hausdorff continua are slightly different beasts, and both concepts exists in literature. 
Adding a property "continuum" without specifying that its a Hausdorff continuum would be confusing to people searching up the term.

**Comment by StevenClontz** [comment]
I also support two propeties: *Hausdorff continuum* and *metrizable continuum*; this is the common disambiguation within the research circles I hang out.

I'm less interested in a dedicated $T_1$ continuum.

**Comment by StevenClontz** [comment]
In today's community call, we decided to start by adding a single (Hausdorff) continuum property, at least for now.
