### ISSUE TITLE
Remove redundant traits (unless they have valuable proofs/references)

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#62]
See discussion in #55

**Comment by prabau** [comment]
Ideally traits that have valuable proofs/references but are also deduced could have the web site show both the explanatory text and the deduction.  But that would be a longer term feature for the general pi-base infrastructure, maybe not so easy to do and not a high priority.

**Comment by StevenClontz** [comment]
So it's easy to model this: we just leave off the `value:` boolean in the YAML frontmatter. Then if the result is deduced, that's great, but if not we can show a `?` with whatever discussion is in the file.

This is probably a good way to handle placeholders for results independent of ZFC, since pi-base is only equipped to handle one model of set theory at the moment.

**Comment by StevenClontz** [comment]
After discussion with @jamesdabbs we're going to just have the viewer expose redundancies, and human editors can decide if the redundancy should be removed. https://github.com/pi-base/viewer/issues/73
