### ISSUE TITLE
Steen & Seebach space 94 item 4 says that the space is not P9 functionally Hausdorff

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#623]
@jocelynbell @StevenClontz Note that Steen & Seebach space 94 item 4 says that the space is not [P9](https://topology.pi-base.org/properties/P000009) (functionally Hausdorff).  That is better than quoting the General Reference Chart to assert that the space is not completely regular.

_Originally posted by @prabau in https://github.com/pi-base/data/issues/599#issuecomment-2045903434_

**Comment by GeoffreySangston** [comment]
Assuming [S94](https://topology.pi-base.org/spaces/S000094) has not moved, pi-base now derives Functionally Hausdorff and Completely Regular for S94. This and the previous thread have no other information which will be forgotten by closing this.

**Comment by Moniker1998** [comment]
@GeoffreySangston Space 94 means space 94 in Counterexamples, and not S94, that is S92
However this post still should stay closed, since https://topology.pi-base.org/spaces/S000092/properties/P000009
