### ISSUE TITLE
Eliminating unused properties

### ISSUE THREAD

**Issue by danflapjax** [pi-base/data#626]
As came up in #618 and #619, there are many properties in the database which are lacking any theorems. Their presence makes improving the database harder, as they currently clutter up the list for no value. The following is a complete list of them:
- [ ] [P83](https://topology.pi-base.org/properties/P000083) 	Almost Čech Complete
- [x] [P85](https://topology.pi-base.org/properties/P000085) 	Ascoli
- [ ] [P92](https://topology.pi-base.org/properties/P000092) 	Moving Off Property
- [ ] [P94](https://topology.pi-base.org/properties/P000094) 	q Space
- [ ] [P95](https://topology.pi-base.org/properties/P000095) 	I-tactic Banach-Mazur
- [ ] [P96](https://topology.pi-base.org/properties/P000096) 	II-tactic Banach-Mazur
- [x] [P102](https://topology.pi-base.org/properties/P000102) 	Semimetrizable
- [ ] [P104](https://topology.pi-base.org/properties/P000104) 	K Analytic
- [ ] [P105](https://topology.pi-base.org/properties/P000105) 	Angelic
- [ ] [P106](https://topology.pi-base.org/properties/P000106) 	Strictly Angelic
- [ ] [P107](https://topology.pi-base.org/properties/P000107) 	Pointwise Countable Type
- [ ] [P108](https://topology.pi-base.org/properties/P000108) 	Locally Čech Complete
- [ ] [P109](https://topology.pi-base.org/properties/P000109) 	Countable Type
- [ ] [P110](https://topology.pi-base.org/properties/P000110) 	Has A Compact Resolution
- [ ] [P113](https://topology.pi-base.org/properties/P000113) 	kℝ Space
- [ ] [P115](https://topology.pi-base.org/properties/P000115) 	Weakly K Analytic
- [ ] [P117](https://topology.pi-base.org/properties/P000117) 	M Space
- [ ] [P118](https://topology.pi-base.org/properties/P000118) 	Pseudo-Polish
- [ ] [P119](https://topology.pi-base.org/properties/P000119) 	Z-Compact
- [ ] [P120](https://topology.pi-base.org/properties/P000120) 	r Space
- [ ] [P122](https://topology.pi-base.org/properties/P000122) 	S space

The two approaches we can take for each are to either delete them or to properly flesh them out. The only one of particular interest to me is semimetrizability, but I felt I should share the list for discussion if any items are of interest to others.

**Comment by Moniker1998** [comment]
Two theorems I propose:

metrizable => semimetrizable
orderable + semimetrizable => metrizable (Creede in his disseration according to [this article](https://www.ams.org/journals/proc/1969-022-02/S0002-9939-1969-0248761-1/S0002-9939-1969-0248761-1.pdf))

**Comment by StevenClontz** [comment]
In today's community call, we decided to purne these, *unless* someone wants to adopt one or more by checking the box above, and commenting here with the properties you've adopted. Then you'll have some time to add theorems and space-property pairs so that the property meets our modern standard for inclusion in the pi-Base: https://github.com/pi-base/data/wiki/Reviewing#requirements-for-a-new-property

**Comment by prabau** [comment]
Property I'd like to see in pi-base: Ascoli

**Comment by Moniker1998** [comment]
I assume @danflapjax will adpot the semimetrizable property, which is the only one I care about, and probably will do a better job than I would at adding relevant theorems. So I won't adopt any property.

**Comment by StevenClontz** [comment]
I remembered this thread as I opened #861 - reopening this issue until my PR is merged or until Ascoli and Semimetrizable are connected to the rest of pi-Base.

**Comment by StevenClontz** [comment]
Dropping https://www.ams.org/journals/proc/1961-012-05/S0002-9939-1961-0125562-9/S0002-9939-1961-0125562-9.pdf as a consice reference for showing metrizable=>semimetrizable=>first-countable, as well as an example of a semi-metrizable space which is not metrizable.
