### ISSUE TITLE
metrizable + realcompact => non-measurable cardinality

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#632]
Hi I'd like to replace [theorem 394](https://topology.pi-base.org/theorems/T000394) by the stronger

P53 metrizable + P162 realcompact => P164 non-measurable

I don't think it exists in literature, [here's the math stackexchange link](https://math.stackexchange.com/questions/4902389/a-metrizable-space-is-realcompact-iff-it-has-non-measurable-cardinality/4902390) for the proof

I've also asked for a better reference of this [here](https://mathoverflow.net/questions/469593/reference-if-x-is-metrizable-then-x-is-realcompact-iff-x-is-non-measur)

**Comment by Moniker1998** [comment]
I've got a response, K.P. Hart gave a very simple proof of this using Shirota's theorem
[See here](https://mathoverflow.net/a/469610/150060)
I think this answer would be great for a reference. Shirota's theorem can be found in Gillman and Jerison

**Comment by GeoffreySangston** [comment]
This one is also still open as of today, and looks like everything is set up to add it. I would do it but it's pretty far from the objects I normally study so I probably wouldn't do a good job.

[π-Base, Search for `metrizable + realcompact + ~Non-measurable cardinality`](https://topology.pi-base.org/spaces?q=metrizable+%2B+realcompact+%2B+%7ENon-measurable+cardinality)
