### ISSUE TITLE
General proof for S20,34,36/P16, S35/P19, S36/P103

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#659]
Does it worth to give some more general fact to the ordinal spaces? I mean:
$\bullet$ Adding to S20,34,36/P16 a sentence like "More generally, an {P190} (ordinal space) is {P16} (compact) if and only if it is not a limit ordinal";
$\bullet$ Adding to S35/P19 a sentence like "More generally, an {P190} is {P19} (countably compact) if and only if its cofinality is not $\omega$";
$\bullet$ Adding to S36/P103 a sentence like "More generally, an {P190} $\alpha$ is {P103} (strongly KC) if and only if $\alpha\ge\omega_1+1$",
with some relevant references.

**Comment by prabau** [comment]
Hmm, I am not sure it's worth it.  Here is how I view it.  What you mention is all true, but I would say the purpose of S35/P19 for example is to give a reference or a short proof of why P19 holds and does not hold in that space, but not to teach the user about related spaces.  Now if something has a reference and the user wants to follow up on the reference and finds out about related things, that's up to them and all good, but it's not the purpose of pi-base to spell it out for them.  Most readers of S35/P19 will want something to the point without extraneous facts.

On the other hand, in general, if there is a related fact that we want to model as a property in pi-base, and then add theorems and traits and spaces involving that new property, that's a valid approach to be able to mention something about it.  But in this case, I think a property like "ordinal space with a limit ordinal" or "ordinal space with cofinality not $\omega$", etc is just too specialized.  These are properties of ordinal numbers and making them into topological properties does not seem so natural.  Not everything needs/can be modeled in pi-base.

That's my opinion, but please feel free to share yours.

**Comment by Jianing-Song** [comment]
> Hmm, I am not sure it's worth it. Here is how I view it. What you mention is all true, but I would say the purpose of S35/P19 for example is to give a reference or a short proof of why P19 holds and does not hold in that space, but not to teach the user about related spaces. Now if something has a reference and the user wants to follow up on the reference and finds out about related things, that's up to them and all good, but it's not the purpose of pi-base to spell it out for them. Most readers of S35/P19 will want something to the point without extraneous facts.
> 
> On the other hand, in general, if there is a related fact that we want to model as a property in pi-base, and then add theorems and traits and spaces involving that new property, that's a valid approach to be able to mention something about it. But in this case, I think a property like "ordinal space with a limit ordinal" or "ordinal space with cofinality not ω", etc is just too specialized. These are properties of ordinal numbers and making them into topological properties does not seem so natural. Not everything needs to/can be modeled in pi-base.
> 
> That's my opinion, but please feel free to share yours.

I'm totally agreed. Thanks for the explanation!
