### ISSUE TITLE
T488 for GO-spaces

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#663]
It appears to me that a countably compact GO-space must be sequentially compact, and nothing much must be changed in the proof of T488:

> Every sequence in a totally ordered set has a monotone subsequence (see for example {{mathse:1706258}}). The space being {P19} implies that this subsequence has an accumulation point $x$, which must be its limit since $x$ has a local base of order-convex open neighborhoods.

More detailedly, if $x$ is an accumulation point of a monotone sequence $(x_n)\_{n\in\omega}$, and $U$ is an order-convex open neighborhood, then $U$ contains $(x_{n\_k})\_{k\in\omega}$ implies that $U$ contains $x_n$ for $n_0\le n\le n_1$, $n_1\le n\le n_2$ and so on.

Please double check me on this. Thanks!

**Comment by prabau** [comment]
Nice! That will do it.
