### ISSUE TITLE
US versus Sequentially Hausdorff

### ISSUE THREAD

**Issue by prabau** [pi-base/data#67]
This refers to spaces for which converging sequences have a unique limit (https://topology.jdabbs.com/properties/P000099).

Would it be possible to make "US" the name of the property and make "Sequentially Hausdorff" the alias instead?

The terminology "US space" seems a lot more common than "sequentially Hausdorff space".  A search in mathoverflow does not show a single example of "sequentially hausdorff", and shows several with "US space".  mathstackexchange has only one page mentioning "sequentially Hausdorff" in passing, as a synonym for US, and several dozen pages for US.  Same thing when searching articles in Google (and even one article uses sequentially Hausdorff with a entirely unrelated meaning of separating points by sequentially open sets). Even the article used as reference in https://topology.jdabbs.com/properties/P000099 uses the US terminology.

The US terminology was introduced in https://www.jstor.org/stable/2316017 (Wilansky 1967).
Do you know where sequentially Hausdorff comes from?

**Comment by StevenClontz** [comment]
Yeah, while I prefer verbosity in default naming when possible, I'd accept a pull request making US the main name as there doesn't seem to be a standard verbose alias.

Interestingly https://www.researchgate.net/publication/332530524_Sequentially_Hausdorff_and_full_sequentially_Hausdorff_spaces defines "sequentially Hausdorff" differently. It's between T2 and US, but from my quick scan it's unclear if it's equivalent to US.

**Comment by prabau** [comment]
Okay.  I'll do a pull request.

**Comment by StevenClontz** [comment]
Closed by #68
