### ISSUE TITLE
Thomas corkscrew (S92) is not Functionally T_2 (P9).

### ISSUE THREAD

**Issue by Almanzoris** [pi-base/data#681]
Space 92.

It does not show up in the properties list of the space.

P12 set as false could be modified to P9 set as false, since the space is P1 and P6 implies P9.

**Comment by prabau** [comment]
Yeah, that would be a good improvement. And we can quote item 4 for space 94 in Steen & Seebach as justification, which is always better than just saying it's asserted in the General Reference Chart.

At the same time, we can also remove the trait for P129 (indiscrete) = F, which should be deducible.

**Comment by Almanzoris** [comment]
Alright.
