### ISSUE TITLE
shrinking space

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#696]
https://en.wikipedia.org/wiki/Shrinking_space

A property for which it would be nice to have examples for.

Implies: normal, countably paracompact

Implied by: normal metacompact

**Comment by ccaruvana** [comment]
A couple of things to consider about the shrinking property for additional reference:
- According to https://zbmath.org/0712.54016, a submetacompact space is shrinking iff it is normal. Do we want to add in submetacompact to the pi-base as well?
- Are there well-known examples that separate shrinking from the other related properties outlined in the issue? It may be useful to have these in hand to add in with the PR adding in the shrinking property.

**Comment by prabau** [comment]
Submetacompactness seems to be a well-studied property with important connections to other properties.  See for example http://topology.nipissingu.ca/tp/reprints/v03/tp03207s.pdf.  Worth having in pi-base.
