### ISSUE TITLE
Locally compact Hausdorff spaces with $G_\delta$ points

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#698]
Locally compact Hausdorff spaces with $G_\delta$ points i.e. with countable pseudocharacter are first countable.

https://math.stackexchange.com/questions/1288595/x-a-locally-compact-haussdorf-space-each-singleton-of-which-is-the-intersection?noredirect=1&lq=1#comment2616696_1288595

There is no property of $G_\delta$-points that I am aware of in pi-base, but there is a property of $G_\delta$-space.

So we have a theorem that doesn't yet exists on pi-base (and $G_\delta$-space could be replaced with countable pseudocharacter in the future):

**Locally compact + Hausdorff + $G_\delta$-space => first countable**

If countable pseudocharacter property is to be added, one can also include:

**$T_1$ + first countable => countable pseudocharacter**

**Comment by prabau** [comment]
FYI, @Almanzoris is working on this as part of #695 and related PR. It's work in progress. And thanks for the reference.  That will be useful.

**Comment by Moniker1998** [comment]
Ah. That makes a lot of sense. I'll close the issue then

**Comment by prabau** [comment]
Feel free to comment on #695 if you have any opinion.
