### ISSUE TITLE
Make UIDs match Counterexamples

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#7]
Where possible, it'd be nice to have our UIDs match Counterexamples in Topology. This won't be completely possible, as some counterexamples are somewhat loosely defined (e.g. we will need to tighten one-point compactification of an uncountable discrete space to be of cardinality omega_1). But it's a nice gesture.

**Comment by StevenClontz** [comment]
I think this idea probably should be abandoned; it's probably not worth the effort to get done before next week, and there are several cases where there won't be a 1-1 correspondence anyway (several spaces are actually functors defining spaces based on a general class of spaces). @jamesdabbs feel free to reopen if you disagree.

We do have *Counterexamples* references in the metadata, so we could in fact support an easter egg like /counterexamples/## which redirects to the appropriate /spaces/S######, but I think the ship has sailed on making those numbers match.

**Comment by jamesdabbs** [comment]
Agreed. I think the counterexamples metadata field is the more flexible way to handle this anyways. We can always support routes like `spaces/cx/63` or something down the road, if we decide that's desirable.
