### ISSUE TITLE
Adding a local generalization of homogeneity

### ISSUE THREAD

**Issue by danflapjax** [pi-base/data#708]
As mentioned in #706, it would be nice to have a property to describe the idea of local neighborhoods being the same across an entire space, since certain theorems involving [homogeneity](https://topology.pi-base.org/properties/P000086) can be generalized, as well as to provide a sufficient condition for a locally Euclidean space being locally n-Euclidean. Despite a handful of relevant questions on math.stackexchange.com, I have been unable to find a single published paper regarding any property of this sort, so the following is based on my own thoughts.

The most obvious and natural option to me is if you can choose a neighborhood $U_x$ of each point $x\in X$ such that for any two $a,b\in X$ there is a homeomorphism $f:U_a\rightarrow U_b$ that maps $a$ to $b$. This is implied by homogeneity by simply taking $U_x=X$. The name I'd expect most would be "locally homogeneous", but this is used more often for spaces with a basis of homogeneous sets. [This question](https://math.stackexchange.com/questions/2756007/connected-locally-homogenous-space-which-is-not-globally-homogenous) gives a variation which seems inequivalent, and it's not hard to come up with further variations.

Here are some example theorems (using locally homogeneous, for lack of an alternate term):
- Homogeneous ⇒ Locally homogeneous
- Has an isolated point ∧ Locally homogeneous ⇒ Discrete (refining [T209](https://topology.pi-base.org/theorems/T000209))
- Locally Euclidean ∧ Connected ⇒ Locally homogeneous
- Alexandrov ∧ Locally homogeneous ⇒ R0 (and therefore Partition topology) ∧ Homogeneous

Just the other night it occurred to me that you could also use a property that there exists a basis (or perhaps prebasis) of sets which are all homeomorphic to each other. I have not had the chance to research the web or literature for this. It should imply the previous property under the assumption that the space is also [strongly locally homogeneous](https://www.ams.org/journals/proc/1982-084-01/S0002-9939-1982-0633296-0/S0002-9939-1982-0633296-0.pdf), but I don't know how they relate otherwise. Both of them do also resemble the idea of a [(G,X)-space](https://en.wikipedia.org/wiki/(G,X)-manifold), but unfortunately we can't simply use that as a property, since any space is one if we let $X$ be the space itself and $G$ be trivial.

I would love to hear of any published work relating to this subject, or any feedback on these properties' relevance to Pi-Base. I know certain simple properties not appearing in the literature have made their way into the database, but for this nontrivial of a property, I would feel uncomfortable being completely divorced from prior work.

**Comment by GeoffreySangston** [comment]
The article by Bing and Borsuk titled _Some Remarks Concerning Topologically Homogeneous Spaces_ studies the version of *locally homogeneous* which is proposed in the original post. The following propositions from it could be added to pi-base if pi-base ever adds the missing properties (i.e., AR space, ANR space, some version of 2-dimensional)

Corollary 8.2: For dimensions $n = 0, 1, 2$ every connected, n-dimensional, locally compact, locally contractible and locally homogeneous space $X$ is a manifold.

Corollary 8.3: 2-dimensional + compact + manifold is equivalent to 2-dimensional + locally homogeneous + compact + ANR space

Corollary 8.4: 2-dimensional + compact + AR space implies ~locally homogeneous

I didn't look too closely. Maybe some other statements can be drawn from this article.
