### ISSUE TITLE
Second countable + Sequentially compact implies Compact

### ISSUE THREAD

**Issue by prabau** [pi-base/data#72]
(Second countable + Sequentially compact) implies Compact.
This is confirmed by doing a space search for "Second Countable+Sequentially Compact+~Compact" and getting a response that it's impossible because:
- T000125: Second countable implies Lindelof + First countable + Separable
- T000003: Sequentially compact implies Countably compact
- T000106: Lindelof + Countably compact implies Compact

Therefore in T000060 (Sequentially compact + Second countable + T1 implies Compact) the T1 hypothesis is superfluous, and since T000060 can then be derived from the other theorems, it does not serve much purpose and I propose to remove it.

Please let me know if you agree.

**Comment by StevenClontz** [comment]
Sounds reasonable - only sticking point would be if one of T3/T106/T125 should actually have the T1 assumption as well. Either way a PR to remove T60 sounds good, and I'd appreciate some thought about whether we need to add T1 to any of other three if you haven't already.

**Comment by prabau** [comment]
I examined T3/T106/T125 and they don't need the T1 assumption.  They are pretty standard results too.  So it should be fine to remove T60.  I'll do a pull request.
