### ISSUE TITLE
Theorem Suggestion: Discrete Finite Space implies Spectral Space

### ISSUE THREAD

**Issue by konradvoelkel** [pi-base/data#743]
## Theorem Suggestion

If a space is:

- [P52](https://topology.pi-base.org/properties/P000052)
- [P78](https://topology.pi-base.org/properties/P000078)

then it is [P75](https://topology.pi-base.org/properties/P000075).

## Rationale

This theorem would demonstrate that no spaces satisfy the following search:

https://topology.pi-base.org/spaces?q=Discrete+%26+Finite+%26+%7E+Spectral+space

## Proof/References

The result is trivial, as discrete and finite already imply sober and compact, and the whole powerset is the collection of compact open sets, which trivially forms a basis for the topology and is closed under finite intersections.

It can also be deduced from the more powerful statement (Proposition 10 in Melvin Hochster's 1967 thesis "Prime ideal structure in commutative rings" which states) "X is spectral iff it is a projective limit of finite T0 spaces." by observing that all finite discrete spaces are projective limits of finite T0 spaces.

**Comment by Moniker1998** [comment]
What about Hausdorff zero-dimensional compact sober space implies spectral space?
