### ISSUE TITLE
$\ell^2$ with weak topology is $T_6$

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#748]
I've been searching for spaces for which separation axioms are unknown.

I've noticed that for S21 which is $\ell^2$ with weak topology, it's not known if it's $T_5$ or $T_6$.

That's why I proved and posted a question-answer that it is $T_6$.

Use it as reference (or something better if you can find it, but I couldn't).

https://math.stackexchange.com/questions/4968645/separation-properties-of-weak-topology-on-ell2

**Comment by prabau** [comment]
Thanks! That will be good to add.

**Comment by Moniker1998** [comment]
Actually it seems like this addition won't be needed.

https://github.com/pi-base/data/issues/749

I checked the theorems, and countable network will imply perfect normality of $\ell^2$ with weak topology.

**Comment by prabau** [comment]
Yes! $\sigma$-space implies $G_\delta$-space: https://topology.pi-base.org/theorems/T000496

See #676

**Comment by prabau** [comment]
I am not sure if $\sigma$-space implies normal.  But cosmic spaces are always T6, which would apply in this case.

https://topology.pi-base.org/spaces?q=cosmic%2B%7ET6
