### ISSUE TITLE
Theorem Suggestion: metrizable implies aleph-space

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#750]
## Theorem Suggestion

If a space is:

- [P53](https://topology.pi-base.org/properties/P000053)

then it is [P178](https://topology.pi-base.org/properties/P000178).

## Rationale

The theorem is not here yet.

## Proof/References

Every metrizable space has a $\sigma$-locally finite basis. This is also a $\sigma$-locally finite $k$-network.

**Comment by prabau** [comment]
I was well aware that we need to add this result.  But thanks for prodding me.

**Comment by prabau** [comment]
(I was waiting for other results involving this circle of ideas to get approved, but the reviews have been kind of slow :-)

**Comment by prabau** [comment]
Actually, [metrizable ==> aleph-space] is already known to pi-base:
https://topology.pi-base.org/spaces?q=metrizable%2B%7E%24%5Caleph%24-space

If you were working from a browser that had not been closed in a long time, the pi-base version was probably stale.  Remedy: Advanced tab, click on Reset.

**Comment by Moniker1998** [comment]
Ah. I should click the reset button more often then. Sorry for the unnecessary raise of issue
