### ISSUE TITLE
S139, R/Z is a cosmic space

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#752]
Since R/Z [S000139](https://topology.pi-base.org/spaces/S000139) is a continuous image of a separable metrizable space R, it's a cosmic space.

**Comment by yhx-12243** [comment]
Already resolved in ebd2b18.

https://topology.pi-base.org/spaces/S000139/properties/P000074

![Countable bouquet of circles is Cosmic](https://github.com/user-attachments/assets/5f86c9de-fbc7-4a7a-bd4a-8f069fd2cd2d)
