### ISSUE TITLE
Issue with path-connectedness of long ray and others

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#753]
I've tried to click on the logic why closed long ray is not metrizable.
It's because it's not path-connected, and clicking on the space showed me that much.
But other time if I click on the space it shows it's path-connected!

There seems to be some kind of issue with pi-base.

**Comment by prabau** [comment]
Can you give specific links showing the problem?

For example, the closed long ray is not metrizable, but the proof in pi-base does not involve path-connectedness:
https://topology.pi-base.org/spaces/S000039/properties/P000053
(but I would agree the justification in this case needs to be fixed)

**Comment by Moniker1998** [comment]
![Zrzut ekranu 2024-09-08 082740](https://github.com/user-attachments/assets/f3441218-957f-4a8e-87fb-442788153f2f)
Here is a screenshot from the same link

**Comment by Moniker1998** [comment]
I think I fixed it by clicking on "sync" in the tab "advanced". It now shows that it uses that the closed long ray is not first countable.
