### ISSUE TITLE
Long circle is T_5 but not T_6

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#754]
https://topology.pi-base.org/spaces/S000196

Clearly $\omega_1$ is a subspace of the long circle so its not $T_6$
Moreover, any its proper subspaces is a subspace of a LOTS, so normal.

**Comment by StevenClontz** [comment]
I'm sure this is easy to see, but why is $T_6$ hereditary? We should note this meta-property. @prabau

**Comment by Moniker1998** [comment]
@StevenClontz If $Y\subseteq X$ and $A \subseteq Y$ is closed, then $\overline{A}$ is a zero-set of $X$, so $A = \overline{A}\cap Y$ is a zero-set of $Y$. 
Now, any two disjoint sets can be separated by open neighbourhoods - this is easy to show. So $Y$ is normal.
Any any zero-set is also a $G_\delta$-set, so $Y$ is perfectly normal.
