### ISSUE TITLE
K-topology (S56) is $\sigma$-connected (P189)

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#769]
The proof is exactly the same as K-topology is connected. This is because $\sigma$-connectedness share two similar properties as connectedness:

$\bullet$ If $\\{A_\alpha\\}$ is a family of $\sigma$-connected sets with nonempty intersection, then $\cup A_\alpha$ is $\sigma$-connected.

Proof: Write $\cup A_\alpha = \bigcup_{n=1}^\infty C_n$, where $\\{C_n\\}$ is a family of closed subsets with respect to the subspace topology of $\cup A_\alpha$, then for each $\alpha$, $\\{A_\alpha\cap C_n\\}$ is a family of closed subsets with respect to the subspace topology of $A_\alpha$. So each $A_\alpha$ must belong to the same $C_n$.

$\bullet$ The closure of a $\sigma$-connected set is $\sigma$-connected.

Proof: Let $E$ be a $\sigma$-connected set of a topo space $X$, and write $\overline{E}=\bigcup_{n\in\omega} C_n$, , where $\\{C_n\\}$ is a family of closed subsets with respect to the subspace topology of $\overline{E}$. Since $\overline{E}$ is closed, each $C_n$ is also closed. Here $\\{E\cap C_n\\}$ is a family of closed subsets with respect to the subspace topology of $E$, so wlog suppose that $E\cap C_0 = E$ and $E\cap C_n=\emptyset$ for $n>0$, then $\overline{E}\subset C_0$ since $C_0$ is closed.

Now the restriction of $\mathbb{R}_K$ to the subspaces $(-\infty,0]$ and $(0,+\infty)$ coincides with their counterparts in standard topology, so both subspaces are $\sigma$-connected per T486. We see that $[0,+\infty)=\overline{(0,+\infty)}$ and $\mathbb{R}_K = (-\infty,0]\cup[0,+\infty)$ are also $\sigma$-connected.

**Comment by prabau** [comment]
Just looked at this.  These two propositions are very useful.  This should be in a mathse post that we can later refer to, showing that the K-topology on $\mathbb R$ is sigma-connected.
Let me know if you want me to do anything.

**Comment by prabau** [comment]
By the way, while we are updating K-topology, it would be good to replace the justification for some of the properties with references to something better than just quoting the "General Reference Chart" from Steen & Seebach.  In particular for connected and path connected.

I have also been wondering which one is a better primary name.  Maybe "K-topology on $\mathbb R$"?  I think that's used in Munkres? and many mathse post refer to that name due to that.  But it seems both names are used in the literature though.
What do you think? @StevenClontz, @ccaruvana?

(not sure where the name of Smirnov comes from here)

**Comment by prabau** [comment]
https://mathoverflow.net/questions/96794/smirnovs-deleted-sequence-topology

**Comment by prabau** [comment]
Actually, combining your observations with T485, doesn't that show
[arc connected + T2 ==> sigma-connected] ?

**Comment by Jianing-Song** [comment]
> Actually, combining your observations with T485, doesn't that show [path connected + T2 ==> sigma-connected] ?

Speaking of that, isn't just path-connectedness is enough?

Claim: The image of a σ-connected set is σ-connected set. This is essentially because preimage of the union is the union of preimages.

Let $X$ be a path-connected space and fix $x_0\in X$. Suppose that $X=\bigcup_{n\in\omega} C_n$, where $\\{C_n\\}$ is a disjoint family of close subsets, and WLOG suppose that $x_0\in C_0$. For Every $x\in X$, let $\gamma_x:[0,1]\to X$ be a path connecting $x_0$ and $X$, then $\gamma_x([0,1])$ is σ-connected, but $\\{\gamma_x([0,1])\cup C_n\\}$ forms a partition into closed subsets of it, so $\gamma_x([0,1])\subset C_0$ since $\gamma_x([0,1])\cup C_0\noteq\emptyset$, and in particular $x\in C_0$. We then have $X=C_0$ since $x$ is arbitrary.

Hausdorffness seems to be unnecessary because we didn't need that $\gamma_x([0,1])$ to be closed in $X$. Please double check me on this (not sure if I had a clear mind) :)

**Comment by prabau** [comment]
Nice!  No need for T2 indeed.  

And by using your observation at the top, that the union of any family of sigma-connected sets with nonempty intersection is itself sigma-connected, there is an even easier argument as follows.

If $x$ is a point of a path connected space $X$, the space $X$ is the union of all the paths in $X$ starting at $x$.  Each of these paths is sigma-connected, and $x$ is in all of them.  Hence $X$ is sigma-connected.

**Comment by Jianing-Song** [comment]
> Nice! No need for T2 indeed.
> 
> And by using your observation at the top, that the union of any family of sigma-connected sets with nonempty intersection is itself sigma-connected, there is an even easier argument as follows.
> 
> If x is a point of a path connected space X , the space X is the union of all the paths in X starting at x . Each of these paths is sigma-connected, and x is in all of them. Hence X is sigma-connected.

Yes, tmy idea was just that. So perhaps you could ask a question on Math SE, and I will write an answer tomorrow?

**Comment by prabau** [comment]
https://math.stackexchange.com/questions/4975686/sigma-connected-spaces-and-path-connected-property

**Comment by Jianing-Song** [comment]
> https://math.stackexchange.com/questions/4975686/sigma-connected-spaces-and-path-connected-property
> 
> Feel free to put anything you deem useful in your answer, like the various little lemmas above.

Thanks, I will add an answer. But K-topology in this issue is not path-connected, so its status is not directly settled by this problem. Would you like to give a proof in my answer that K-topology serves as a non-path-connected σ-connected space, or would you like to ask a separate question?

**Comment by prabau** [comment]
> But K-topology in this issue is not path-connected, so its status is not directly settled by the question itself. Would you like to give a proof in my answer that K-topology serves as a non-path-connected σ-connected space, or would you like to ask a separate question?

Nice mathse writeup.  Showing K-topology is sigma-connected is a nice illustration of combining the various lemmas.  Specifically, path components are sigma-connected, and so are their closures. And if two path components have intersecting closures, the union of the closures is also sigma-connected, etc.  Very nice stuff.

**Comment by Jianing-Song** [comment]
> > But K-topology in this issue is not path-connected, so its status is not directly settled by the question itself. Would you like to give a proof in my answer that K-topology serves as a non-path-connected σ-connected space, or would you like to ask a separate question?
> 
> Nice mathse writeup. Showing K-topology is sigma-connected is a nice illustration of combining the various lemmas. Specifically, path components are sigma-connected, and so are their closures. And if two path components have intersecting closures, the union of the closures is also sigma-connected, etc. Very nice stuff.

Glad to see that you are happy with the proof. Thanks!

**Comment by prabau** [comment]
related PR: #781
