### ISSUE TITLE
The Sorgenfrey circle

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#772]
I was considering the space $\mathbb{R}_l/\mathbb{Z}$ (the Sorgenfrey circle). Note that there is no difference between the Sorgenfrey circle and the Sorgenfrey ray: $\mathbb{R}_l/\mathbb{Z}$ is homeomorphic to $[-\infty,\infty)_l$, the set $[-\infty,\infty)$ topologized by the basis consisting of $[a,b)$ with $-\infty\le a<b<+\infty$. In particular, unlike the ordinary cirle, the Sorgenfrey circle is a GO-space.

I think this space is interesting because it arises in probability theory: a distribution function is precisely a continuous function $[-\infty,\infty)_l\to[0,1]$ which is increasing (with respect to the natural order on $[-\infty,\infty)$ which makes $[-\infty,\infty)_l$ a GO-space).

So, what are some interesting properties of the Sorgenfrey circle? :)

**Comment by prabau** [comment]
How do you construct $\mathbb{R}_l/\mathbb{Z}$?  Do you mean $\mathbb{R}_l$ with $\mathbb{Z}$ identified to a point?  Or something else related to the quotient group?

Apart from that, I think the Sorgenfrey ray $[-\infty,\infty)_l$ is homeomorphic to the Sorgenfrey line.

**Comment by Moniker1998** [comment]
I believe that they mean $\mathbb{R}_l$ quotient by relation $x\sim y \iff x-y\in\mathbb{Z}$.

**Comment by prabau** [comment]
It looks like the Sorgenfrey circle is a paratopological group.

The Sorgenfrey line and the Sorgenfrey circle are not even isomorphic as abstract groups (look at elements of finite order).  So they are definitely not "isomorphic" as paratopological groups.  But they are homeomorphic spaces as far as I can tell.

**Comment by Moniker1998** [comment]
Yeah, since $\mathbb{R}_l$ can be decomposed into disjoint union $[n, n+1)$ and the same can be done for the Sorgenfrey circle using that its homeomorphic to $[-\infty, \infty)$. So if anything it would be better to perhaps mention it in the description of the Sorgenfrey line.

**Comment by Jianing-Song** [comment]
> Yeah, since R l can be decomposed into disjoint union [ n , n + 1 ) and the same can be done for the Sorgenfrey circle using that its homeomorphic to [ 0 , 1 ) ⊆ R l . So if anything it would be better to perhaps mention it in the description of the Sorgenfrey line.

Yes, I see the point. Too sleepy last night ...

**Comment by prabau** [comment]
It's similar to the metrizable property:  A space that admits a compatible metric that generates the topology.  But many non-equivalent metrics can generate the same topology.

Same for spaces that admit a compatible group structure, making it into a topological group.  But non-isomorphic topological groups can have the same topology.

And here for paratopological groups.

**Comment by Jianing-Song** [comment]
> It's similar to the metrizable property: A space that admits a compatible metric that generates the topology. But many non-equivalent metrics can generate the same topology.
> 
> Same for spaces that admit a compatible group structure, making it into a topological group. But non-isomorphic topological groups can have the same topology.
> 
> And here for paratopological groups.

That's an interesting observation!
