### ISSUE TITLE
What is a semimetrizable space?

### ISSUE THREAD

**Issue by Almanzoris** [pi-base/data#775]
I was wondering what is the property [semimetrizable](https://topology.pi-base.org/properties/P000102), but I don't have access to the reference.

**Comment by Moniker1998** [comment]
A semimetric is like a metric but doesn't necessarily satisfy triangle inequality.
A semimetrizable space is a space which admits a semimetric that generates its topology, that is there is a semimetric $d$ such that the open balls $B_d(x, r)$ form a neighbourhood basis for $x$.
The article this is referencing is open access so you should find it online, legally.
Also note that open balls in a semimetric space are not necessarily open.

**Comment by Almanzoris** [comment]
Alright. Thank you for the information and the remark.
