### ISSUE TITLE
Space on which every continuous self-bijection is a homeomorphism

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#783]
In case that we don't have this property yet, does the property "every continuous self-bijection is a homeomorphism" looks interesting?

So basically discrete, indiscrete and compact Hausdorff spaces have this property. $\mathbb{R}^n$ also (non-trivially) has this property, see https://math.stackexchange.com/questions/1086974/continuous-bijection-from-mathbbrn-to-mathbbrm. On the other hand, I believe that no infinite-dimensional normed vector space has this property.

**Comment by Moniker1998** [comment]
Interesting or not, I think it should be established in the literature somewhere first
