### ISSUE TITLE
Homogenous spaces

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#787]
https://topology.pi-base.org/spaces?q=%3Fhomogenous

Spaces which are homogeneous:
https://topology.pi-base.org/spaces/S000015 (obvious from definition)
https://topology.pi-base.org/spaces/S000017 (obvious from definition)
https://topology.pi-base.org/spaces/S000018 (product of homogeneous spaces)
https://topology.pi-base.org/spaces/S000019 (obvious from definition since R is)
https://topology.pi-base.org/spaces/S000032 (standard result, see e.g. Infinite-dimensional topology by van Mill)
https://topology.pi-base.org/spaces/S000042 (obvious from definition)

Spaces which aren't homogeneous:
https://topology.pi-base.org/spaces/S000038 (obviously not homogeneous because of the point $(0, 0)$)
https://topology.pi-base.org/spaces/S000039 (not first countable only at $(\omega_1, 0)$
https://topology.pi-base.org/spaces/S000040 (not first countable only at $\infty$)
https://topology.pi-base.org/spaces/S000041 (because $[0, 1]$ isn't)
https://topology.pi-base.org/spaces/S000044 (the amount of open sets to which $x$ belongs must be the same for each $x$)
https://topology.pi-base.org/spaces/S000045 ($0$ belongs to every open set, but there are points which don't)
https://topology.pi-base.org/spaces/S000046 (if $a = 3/2$ and $b = 5/2$ then there are $U, V$ with $a\in U, b\notin U, a\notin V, b\in V$ yet no such neighbourhoods for $a = 1/2$ and $b = 1/4$)

This is just some of the spaces, but there is a lot of them which are easy to decide but have no mention on pi-base. Someone should update this.

**Comment by StevenClontz** [comment]
Making a PR for all the immediate results now.

**Comment by StevenClontz** [comment]
> https://topology.pi-base.org/spaces/S000044 (the amount of open sets to which x belongs to must be the same for each x)

I believe every point belongs to infinitely-many open sets $(0,1-1/n)$ for all $n<\omega$ such that $1/n<1-x$.

**Comment by StevenClontz** [comment]
> > https://topology.pi-base.org/spaces/S000044 (the amount of open sets to which x belongs to must be the same for each x)
> 
> I believe every point belongs to infinitely-many open sets ( 0 , 1 − 1 / n ) for all n < ω such that 1 / n < 1 − x .

Oh, but we can argue about closed sets instead: $2/5$ only belongs to the closed set $(0,1)$, but $3/5$ belongs to the closed sets $(0,1)$ and $[1/2,1)$.

**Comment by Moniker1998** [comment]
Ah yes sorry. I got confused with S44. Yeah, closed sets will do the job.

**Comment by StevenClontz** [comment]
I feel like S44 would be better described as a product of the [left ray topology](https://topology.pi-base.org/spaces/S000042) on $\omega$ with an indiscrete set of size $\mathfrak c$. (And to get the space I think you were thinking of, use the right ray topology instead.)

**Comment by GeoffreySangston** [comment]
Today all of the spaces Moniker1998 mentioned are now known to be homogeneous or not, based on a quick comparison of the list in OP and the list at https://topology.pi-base.org/spaces?q=%3Fhomogeneous

So I think it's fine to close this.
