### ISSUE TITLE
Space suggestion: Infinite earrings

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#792]
The space is defined by $(\mathbb{Z}\times S^1)/\sim$, where $(m,x)\sim (n,y)$ if and only if $x=y=1$. Equivalently, it can be defined as $\mathbb{R}/\mathbb{Z}$, identifying all points of $\mathbb{Z}$.

The space is sequential, not first countable (https://math.stackexchange.com/q/1017757/), and not locally compact (https://math.stackexchange.com/questions/118005/).

**Comment by prabau** [comment]
We already have this space: https://topology.pi-base.org/spaces/S000139

**Comment by StevenClontz** [comment]
We have several spaces including S139 with these properties. https://topology.pi-base.org/spaces?q=Sequential%2B%7EFirst+countable%2B%7ELocally+compact

But we should probably add "countable wedge sum" to the aliases for S139 so it can be more easily found, if that's how folks are searching for it.

**Comment by Jianing-Song** [comment]
By the way (not related to this post), although the space S139 is not homeomorphic to $\displaystyle\bigcup_{n=1}^\infty \{(x,y):(x-n)^2+y^2=n^2\}$, the two spaces are _homotopically equivalent_ (see https://math.stackexchange.com/q/1741457/1039170), meaning that it is actually more difficult to distinguish these two spaces than to distinguish S139 and Hawaii earring.

**Comment by prabau** [comment]
The last space you mention does not seem to be closed in $\mathbb R^2$: it's missing the $y$-axis.  And it does not seem to be locally compact, but neither is S139.  But it is first countable, even second countable as a subspace of $\mathbb R^2$, whereas S139 is not.  It could be possibly be added to pi-base as a contrasting case with S139.  Even more instructive would be to add the Hawaiian earring, I would say.

**Comment by StevenClontz** [comment]
I personally know Hawaiian colleagues who would strongly prefer the so-called "Hawaiian earring" not be called such, so I'll exercise my editorial privilege to say we need a different canonical name for it on the pi-Base. See the conversation at https://en.wikipedia.org/wiki/Talk:Hawaiian_earring (which is as contentious as one might guess such topics on the internet might be). "Infinite earring" (as used by Munkres) is a more semantic description as well.

But yes, I'd like to see this standard example added to pi-Base.

**Comment by Jianing-Song** [comment]
> The last space you mention does not seem to be closed in R 2 : it's missing the y -axis. And it does not seem to be locally compact, but neither is S139. But it is first countable, even second countable as a subspace of R 2 , whereas S139 is not. It could be possibly be added to pi-base as a contrasting case with S139. Even more instructive would be to add the Hawaiian earring, I would say.

Ah yes, I missed the fact that $\bigcup_{n=1}^\infty \\{(x,y):(x-n)^2+y^2=n^2\\}$ is not locally compact. In a metric space, local compactness at a point is equivalent to some closed ball centered at the point being compact, but for this space no such closed ball is compact because $y$-axis is missing. Thanks!

**Comment by Jianing-Song** [comment]
> I personally know Hawaiian colleagues who would strongly prefer the so-called "Hawaiian earring" not be called such, so I'll exercise my editorial privilege to say we need a different canonical name for it on the pi-Base. See the conversation at https://en.wikipedia.org/wiki/Talk:Hawaiian_earring (which is as contentious as one might guess such a topic on the internet would be). "Infinite earring" (as used by Munkres) is a more semantic description as well.
> 
> But yes, I'd like to see this standard example added to pi-Base.

That's a good name. How would you prefer to call $\bigcup_{n=1}^\infty \\{(x,y):(x-n)^2+y^2=n^2\\}$ (I hate to type this space for each time)? "Stretching" infinite earring?

**Comment by StevenClontz** [comment]
> "Stretching" infinite earring?

Possibly, but we first need to do at least one of the following:

1. Find where the space is used in the literature (and use any appropriate canonical name if possible)
2. Find a search query that we cannot answer without this space

(Disclaimer: I'm guilty of introducing https://topology.pi-base.org/spaces/S000199 but I guess that hints at a third possible rationale: it was a convenience in order to provide a useful characterization of https://topology.pi-base.org/spaces/S000044 as a product.)

**Comment by StevenClontz** [comment]
Edited title to reflect where the conversation led to.

**Comment by prabau** [comment]
> I personally know Hawaiian colleagues who would strongly prefer the so-called "Hawaiian earring" not be called such, so I'll exercise my editorial privilege to say we need a different canonical name for it on the pi-Base. See the conversation at https://en.wikipedia.org/wiki/Talk:Hawaiian_earring (which is as contentious as one might guess such a topic on the internet would be). "Infinite earring" (as used by Munkres) is a more semantic description as well.

Yes, I remember that conversation.  With due respect, one could view those who oppose the Hawaiian earring name as driven by a misguided sense of ... something.  I would be curious, are those colleagues you refer to actually native Hawaiians, or whites who think they know better?  The canonical name in the literature is Hawaiian earring, and that should at least be an alias.

**Comment by StevenClontz** [comment]
I won't go into more detail on this forum because they got harrassed for it, but the particular vocal opponent of the name who I have in mind is a native Hawaiian, yes.

I agree it should be an alias; besides, we will likely cite https://en.wikipedia.org/wiki/Hawaiian_earring as a reference.

**Comment by Jianing-Song** [comment]
Sadly, I only find "inverse Hawaiian earring" once on the Internet, in this link: https://mathoverflow.net/questions/43411/homotopical-immersion-of-the-wedge-product-of-countable-many-circles-in-rn

**Comment by StevenClontz** [comment]
My take is that [S201 Infinite earring](https://topology.pi-base.org/spaces/S000201) is important as a well-established example to contrast with [S139 Countable bouquet of circles](https://topology.pi-base.org/spaces/S000139) (and maybe we should add cross references between their descriptions to point this out). But this inverse infinite earring feels less motivated and at this time isn't a useful example to add, unless it is able to answer a question open to pi-Base.

**Comment by StevenClontz** [comment]
I believe this issue is settled; please re-open if I'm overlooking anything.
