### ISSUE TITLE
Property that open sets are totally ordered by set inclusion

### ISSUE THREAD

**Issue by danflapjax** [pi-base/data#796]
As the title says, I think it would be useful to have a property that for any two open sets $U,V$, either $U\subseteq V$ or $V\subseteq U$, i.e. $(\mathcal T_X,\subseteq)$ is a total order. While this suggestion is spurred by the recent additions of S199 and S200, this had been on my mind as it had come up in the book [Spectral Spaces](https://doi.org/10.1017/9781316543870) where it had been characterized as the specialization preorder being total. The property can also be seen as something like "hereditarily connected", i.e. every subspace is connected. It's the sort of property that won't have received much study in its own right, but it's straightforward and underpins several spaces such that I think it warrants inclusion, similar to [P185](https://topology.pi-base.org/properties/P000185) Partition topology.

Some consequences of the property:
* [P39](https://topology.pi-base.org/properties/P000039) Hyperconnected
* [P14](https://topology.pi-base.org/properties/P000014) Completely normal
* [P174](https://topology.pi-base.org/properties/P000174) Well-based
* [P57](https://topology.pi-base.org/properties/P000057) Countable ⇒ [P27](https://topology.pi-base.org/properties/P000027) Second countable
* [P93](https://topology.pi-base.org/properties/P000093) Locally countable ⇒ Cardinality $\leq\aleph_1$
* [P16](https://topology.pi-base.org/properties/P000016) Compact ∧ [P86](https://topology.pi-base.org/properties/P000086) Homogeneous ⇒ [P129](https://topology.pi-base.org/properties/P000129) Indiscrete (compact implies there is a second-largest open set)

**Comment by prabau** [comment]
Yeah, I was thinking about it too.

Before I give comments, could you take a look at the pending #706?  I made one last change and it's just waiting for you to take a look to finalize this.

After that's done, I can make a suggested edit for the pending #746.  Unless you prefer to handle the pending comments yourself?  It would be good to finalize that.

**Comment by StevenClontz** [comment]
I thought about this as a utility property. I think I see immediately that this property implies "hereditarily connected"; is the reverse true as well? Waving hands it makes sense: given every two points, they are either topologically indistinguishable, or a copy of the Sierpenski space, providing the specialization total ordering. If so, I think "hereditarily connected" sounds quite natural (as natural as "[locally pseudometrizable](https://topology.pi-base.org/properties/P000144)") and could be added.

**Comment by prabau** [comment]
I agree, "Has a totally ordered topology" and "Hereditarily connected" seem two good names for it.

**Comment by prabau** [comment]
See https://www.acadsci.fi/mathematica/Vol03/vol03pp185-205.pdf, section 12 (theorems 22, 23, 24).
(https://zbmath.org/0396.54009)

**Comment by danflapjax** [comment]
> I think I see immediately that this property implies "hereditarily connected"; is the reverse true as well?

Explicitly, if there exist two open sets where neither is a superset of the other, then their symmetric difference is disconnected.

**Comment by danflapjax** [comment]
> See https://www.acadsci.fi/mathematica/Vol03/vol03pp185-205.pdf, section 12 (theorems 22, 23, 24). (https://zbmath.org/0396.54009)

That is an excellent source. I was wondering if hyperconnected + completely normal were sufficient conditions but hadn't thought of a proof, so I'm glad to see it confirmed by Theorem 23. I'm also amused by the fact that they mention the exact space I had thought of to show that hyperconnected + normal/ultraconnected is not sufficient. I suppose it would be a good space to add to the database as well. (If we need a name, it's something like the meet of an included point space and an excluded point space, as long as the included and excluded points are different points.)

**Comment by StevenClontz** [comment]
> See https://www.acadsci.fi/mathematica/Vol03/vol03pp185-205.pdf, section 12 (theorems 22, 23, 24). (https://zbmath.org/0396.54009)

This makes the properly clearly appropriate for pi-Base, excellent.
