### ISSUE TITLE
Delete T340: Topological n-manifold => second countable?

### ISSUE THREAD

**Issue by Jianing-Song** [pi-base/data#810]
We already have T461: Topological n-manifold => Embeddable into Euclidean space, and T459: Embeddable into Euclidean space => Second countable. And unlike the $T_2\Rightarrow T_1$ theorem, this T340 does not simplify any proof because it follows merely from the definition.

Any comments?

**Comment by StevenClontz** [comment]
Sounds fine to me.

**Comment by prabau** [comment]
Technically, it is true that T340 (top. n-manifold ==> second countable) is deducible from T461 and T459.  But T461 a highly non-trivial result, while the fact that top. n-manifolds are second countable is an immediate consequence of the definition.  (And T461 makes use of second countability in its proof.)

@StevenClontz, in light of this, if you still think we can remove T340, I would be fine with it.  Just wanted both of you to consider if there would be a better way to approach this?

**Comment by StevenClontz** [comment]
> T461 a highly non-trivial result

TBH I didn't think carefully about this; I suppose I haven't tried proving this myself and underestimated how intricate the result might be. I was coming from the perspective that this result felt "well-known".

**Comment by Jianing-Song** [comment]
> Technically, it is true that T340 (top. n-manifold ==> second countable) is deducible from T461 and T459. But T461 a highly non-trivial result, while the fact that top. n-manifolds are second countable is an immediate consequence of the definition. (And T461 makes use of second countability in its proof.)
> 
> @StevenClontz, in light of this, if you still think we can remove T340, I would be fine with it. Just wanted both of you to consider if there would be a better way to approach this?

I think there is a difference between T340 and $T_2\Rightarrow T_1$. Although $T_2\Rightarrow T_1$ is deduced automatically, a person who wants to know the proof can consult this theorem directly, without having to know all these intermediate terms. However, the case of T340 is different. I mean, no one would need to have a proof of "topological manifolds are second countable", because that is merely what the definition says, so T340 really only serves for automatic deduction. That's why I think it can be replaced by T459 and T461. Of course, it is up to you to decide ultimately :)

**Comment by GeoffreySangston** [comment]
Just going through open issues. My personal view is that T340 Top Manifold => Second countable should stay. I think it's better for someone using the website as a way to explore topology not have the impression that ' Top Manifold => Second' is really a non-trivial theorem, and not part of the definition. I have wondered if pi-base might one day be able to show multiple derivation paths, which could become more useful as the diversity of types of properties increases.

Anyways, it looks like there is some disagreement on this, as in https://github.com/pi-base/data/issues/810#issuecomment-2433003754, so this issue may not be able to be closed without further input from @prabau and @StevenClontz.

**Comment by StevenClontz** [comment]
I think we're leaning towards "keep", so I'm closing. @Jianing-Song may always re-open if they feel there's further discussion to be had.
