### ISSUE TITLE
Completely metrizable theorem 

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#813]
>  Whether the metric fan is completely metrizable came up in our call today. Indeed, for any almost-discrete metrizable space we can choose a metric where the distance between any two isolated points is greater than some fixed $\epsilon>0$, so any Cauchy sequence is either eventually constant or converges to the one non-isolated point. (Constructively: given some metric $d(x,y)$, take $d\prime(x,y)$ that equals 1 when $x$ and $y$ are both isolated and $\min(1,d(x,y))$ otherwise.) Since this is a theorem we can add later, I see no need to add a trait now.

_Originally posted by @danflapjax in https://github.com/pi-base/data/issues/804#issuecomment-2423719412_

**Comment by prabau** [comment]
This is pending the introduction of "almost discrete".  See #807.

**Comment by StevenClontz** [comment]
From that conversation, I'd pitch these theorems:

- Almost discrete + first countable => metrizable
- Almost discrete => strong Choquet
- metrizable + strong Choquet => completely metrizable

I think http://at.yorku.ca/b/ask-a-topologist/2002/0254.htm says [P63](https://topology.pi-base.org/properties/P000063) implies strong Choquet, so we could weaken the assumptions of [T132](https://topology.pi-base.org/theorems/T000132).
