### ISSUE TITLE
Are S30 and S106 homeomorphic by Anderson–Kadec theorem?

### ISSUE THREAD

**Issue by yhx-12243** [pi-base/data#829]
By [Anderson–Kadec theorem](https://en.wikipedia.org/wiki/Anderson%E2%80%93Kadec_theorem), S106 (C[0, 1]), as an infinite-dimensional separable Banach space, is homeomorphic to the separable Hilbert space l^2.

So is it necessary to deduplicate them?

**Comment by yhx-12243** [comment]
Suggestion: Maybe we can do the property checking for all spaces pairwisely, if there are two with exactly same √/×/?, we should inspect more that whether they may be homeomorphic, or add some property to claim that it is not homeomorphic.

**Comment by StevenClontz** [comment]
More generally, it'd be great if we could clearly see when two spaces in the pi-Base are not distinguished by their properites. A quick glance-through did not reveal any distinguishing properties, but I wasn't careful in my search.

**Comment by yhx-12243** [comment]
> More generally, it'd be great if we could clearly see when two spaces in the pi-Base are not distinguished by their properites. A quick glance-through did not reveal any distinguishing properties, but I wasn't careful in my search.

I've been done a search, and following is what I discovered:
[S66](https://topology.pi-base.org/spaces/S000066) and [S73](https://topology.pi-base.org/spaces/S000073) have the exactly same properties set. Let $\varphi$ be a homeomorphism from S66 to S73, then WLOG $\varphi(0) = (0, 0)$, $\varphi(0^*) = (1, 0)$. Then if we delete both of them, the remaining subspace of S66 is not simply-connected, while S73 is.
[S115](https://topology.pi-base.org/spaces/S000115) and [S117](https://topology.pi-base.org/spaces/S000117) too, but S117 is [contractible](https://en.wikipedia.org/wiki/Contractible_space) while S115 is not.
[S116](https://topology.pi-base.org/spaces/S000116), [S119](https://topology.pi-base.org/spaces/S000119), [S120](https://topology.pi-base.org/spaces/S000120) share the same properties set, and:
* S116 is not homeomorphic to S119, if we consider the "simple" path-connected component, S116 is $\left( \dfrac 12, 1 \right]$, S119 is $\mathbb R$.
* They are not homeomorphic to S120 since S120 has infinite many path-connected components while S116/S119 has only two.

**Comment by yhx-12243** [comment]
Should we merge S106 into S30 and delete S106?

**Comment by StevenClontz** [comment]
I am not super experienced with functional analysis, so this theorem is new to me. It's worth noting that the theorem under discussion is from 1975, which explains why it was not known to Steen and Seebach and their students when writing *Counterexamples*.

I'm inclined to merge homeomorphic spaces: even when characterized quite differently, it's nice to be able to assert their traits in a single place, using whichever characterization is most convenient. What are others' thoughts?

**Comment by prabau** [comment]
I am not opposed to that at all.  We have followed that approach several times already, for example in
- https://topology.pi-base.org/spaces/S000027
- https://topology.pi-base.org/spaces/S000028

The reason I wanted to discuss this here is to ensure there is a discussion first, instead of people going off doing their own thing without first checking for guidance.  But as long as it's properly referenced, it should be fine.

**Comment by StevenClontz** [comment]
Then I think @yhx-12243 can mark the PR as ready for review now, assuming they're still happy with it.
