### ISSUE TITLE
Reword characterizations to not use the object's name

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#83]
An extension of #74 -- it's a waste of space to say things like "A space X is compact if for every open cover of X there exists..." when we could get to the point: "For every cover of the space X there exists...". This also has the advantage of removing the reference to a canonical name for the space/property, which may change later. (Though we still eventually need support for e.g. `{P123}` to display the current canonical name for property 123.)

**Comment by prabau** [comment]
Can we close this issue?
