### ISSUE TITLE
S101 and S1103 is not pseudocompact

### ISSUE THREAD

**Issue by Moniker1998** [pi-base/data#833]
Let $N = \\{ x \in \omega^\kappa : x_k = 0, k\geq 2\\}$ where $\kappa\geq 1$ is a cardinal.

If $f:N\to \mathbb{R}$ is a function, then $\tilde{f}:\omega^\kappa\to\mathbb{R}$ defined by $\tilde{f}(x) = f(\tilde{x})$ where $\tilde{x}_k = x_k$ for $k = 1$ and $\tilde{x}_k = 0$ otherwise is continuous and extends $f$.

So $N$ is a $C$-embedded copy of $\mathbb{N}$, and so $\omega^\kappa$ is not pseudocompact.

**Comment by StevenClontz** [comment]
Thanks for the observation @Moniker1998 - I'm going to ask this question on Math.SE to put more eyes on the argument.

https://math.stackexchange.com/questions/4991556/does-every-product-of-copies-of-mathbb-z-fail-to-be-pseudocompact
