### ISSUE TITLE
Remove redundant UID field for objects?

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#84]
Right now the UID is shown in both the filename and the metadata. Pi-base yells if these don't match, but do we really need it both places?

**Comment by prabau** [comment]
By object, I assume you mean the spaces, theorems and general properties (but not the "traits" per object, where it's not needed).  It is true that it could be determined from the file names, but I don't see a problem with having it also as a uid attribute in the file itself.  It allows to see what the uid is by only looking at the contents of the file.  Somehow it feels like it provides a consistency check that could be useful, for example if someone does a cut and paste of one object into another one, it forces them to pay attention to updating the uid.  But one could go either way, I guess.  You guys with knowledge of the internals of the pi-base infrastructure will be better able to judge.

**Comment by StevenClontz** [comment]
Discussed Jan 18 2024 and decided to keep redundancy to serve as a double-check when copy-pasting from other files.
