### ISSUE TITLE
S000186 is scattered

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#858]
> I think https://topology.pi-base.org/spaces/S000186 is totally disconnected. It is constructed to fail locally Hausdorff.

_Originally posted by @StevenClontz in https://github.com/pi-base/data/issues/857#issuecomment-2458409787_

**Comment by Almanzoris** [comment]
This space is $T_1$. Could it be that S186 is scattered?

When it says that $Y \times \omega$ is open with the product topology, what topology does $\omega$ have? The discrete?

**Comment by StevenClontz** [comment]
> This space is T 1 . Could it be that S186 is scattered? If it is, it would imply that it is totally disconnected.

Since https://topology.pi-base.org/spaces/S000097/properties/P000051 holds, I believe so. Good catch.

> When it says that Y × ω is open with the product topology, what topology does ω have? The discrete?

Yes: equivalently, it's the disjoint union of $\omega$ copies of $Y$.
