### ISSUE TITLE
git problem due to vertical bar in branch names

### ISSUE THREAD

**Issue by prabau** [pi-base/data#875]
@StevenClontz @GeoffreySangston 
I am having problems with trying to update the repository on my machine from the command line.  `git pull` complains, probably due to the use of `|` as part of branch names.

![image](https://github.com/user-attachments/assets/903d909c-7f16-459a-91d5-2eb8f79f9790)

Can you change the name of your branches `S182|P87` and `StevenClontz/S6|P152` ?

**Comment by StevenClontz** [comment]
Relevant: https://stackoverflow.com/questions/68772379/git-rename-files-with-illegal-characters?origin=serp_auto#68778864

I think avoiding pipes in Branch names is a good idea moving forward. Is it plausible to finish these prs as is though? Otherwise I think the old prs with the old branch name needs to be closed.

**Comment by prabau** [comment]
I thought changing the name of the branch will automatically carry to any existing PR.

But anyway, what are the relevant PRs?  If they are ready, I can try to review them.

**Comment by prabau** [comment]
@StevenClontz #869 will eventually be closed anyway, right?  So would it be possible to change the branch name now?
It would be an instructive experiment to see what happens to the PR.

**Comment by GeoffreySangston** [comment]
I'm currently trying to commit and push on the 'S182-has-P87' branch. When I do so, I get the message, 'Unable to commit Source: Remote Repositories'. Is that related to this problem?

**Comment by StevenClontz** [comment]
![image](https://github.com/user-attachments/assets/b2fccda4-ef9d-48bb-802e-1dfe89a39e1c)

**Comment by StevenClontz** [comment]
Both branches are now renamed; let's remember to avoid pipes in branch names in the future (I'll make a note on the wiki).
