### ISSUE TITLE
Add projective plane

### ISSUE THREAD

**Issue by danflapjax** [pi-base/data#893]
> Great suggestion; I've been meaning to add this for a while since it would give an example of a nontrivial [homogeneous space with the fixed point property](https://topology.pi-base.org/spaces?q=Homogeneous+%2B+Fixed+point+property). (The real projective plane would be another nice one to add, but that's worthy of a separate issue.)

_Originally posted by @danflapjax in https://github.com/pi-base/data/issues/760#issuecomment-2344394836_

**Comment by GeoffreySangston** [comment]
Also mentioned here https://github.com/pi-base/data/issues/874#issuecomment-2463483560
