### ISSUE TITLE
regular+2nd countable => pseudometrizable => perfectly normal ?

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#90]
I assert the first implication in a comment here https://math.stackexchange.com/questions/3844039/what-topological-properties-are-trivially-vacuously-satisfied-by-any-indiscrete/3844184#comment7929993_3844050 but want a sanity check before I add it to the community answer and then pi-Base. The 2nd implication also seems valid but could use some more thought.

In general we have nothing on https://topology.pi-base.org/properties/P000121 so these theorems would help, and would generalize https://topology.pi-base.org/theorems/T000029

**Comment by StevenClontz** [comment]
(I think the proofs could be written like this: take the T0 quotient, then each theorem holds for the T0 variants, so then pull back.)

**Comment by prabau** [comment]
The first implication and the proof be taking the Kolmogorov quotient seem correct to me.
Also see https://math.stackexchange.com/a/2040676/52912 which mentions the same thing:

> "By the Urysohn metrization theorem in the non-Hausdorff setting, every regular second-countable topological space is pseudometrizable."

And the second implication also seems to follow from the usual argument
https://math.stackexchange.com/questions/73609/is-a-metric-space-perfectly-normal
combined with taking the T0 quotient and back.

Adding the theorem (pseudometrizable + T0 implies metrizable) could be useful (quite simple, but mentioned for example in Engelking p. 249) and maybe also (metrizable implies pseudometrizable).

**Comment by prabau** [comment]
J. Kelley, _General Topology_, Exercise K, p. 134:

> "Each pseudometrizable space is perfectly normal."

**Comment by prabau** [comment]
One more thing, at the same time would it be possible to explicit spell out the definition of pseudometrizable in https://topology.pi-base.org/properties/P000121 and replace the current reference with just Willard (defined in 3.2(a))?

**Comment by prabau** [comment]
For an additional reference if desired: "by Urysohn’s metrisation theorem a second countable regular space
is pseudo-metrisable" at the top of p. 23 in https://arxiv.org/pdf/math/0412558.pdf
