### ISSUE TITLE
Theorem Suggestion: Ordinal spaces are not Dowker

### ISSUE THREAD

**Issue by eT3q** [pi-base/data#916]
*Modify the below template for your theorem suggestion:*

## Theorem Suggestion

If a space is:

- [P190](https://topology.pi-base.org/properties/P000190)

then it is not [P127](https://topology.pi-base.org/properties/P000127).

## Rationale

This theorem would demonstrate that no spaces satisfy the following search:

https://topology.pi-base.org/spaces?q=Ordinal+space%2BDowker

## Proof/References

See [this Math.StackExchange post](https://math.stackexchange.com/questions/4965715).

**Comment by prabau** [comment]
Thanks for the suggestion.

**Comment by david20000813** [comment]
With the addition of monotonically normal and related theorems, this is now automatically deduced in pi-Base: https://topology.pi-base.org/spaces?q=Ordinal+space+%2B+Dowker
