### ISSUE TITLE
Space Suggestion: Deleted Sequence of Intervals Topology

### ISSUE THREAD

**Issue by david20000813** [pi-base/data#926]
## Space Suggestion

Let $A = \bigcup_{n = 1}^\infty [\frac{1}{3^{n-1}}, \frac{2}{3^n}]$. The **Deleted Sequence of Intervals Topology** is the topology on $\mathbb{R}$ generated by Euclidean open sets and $A^c$.

## Rationale

While this is a new construction (as far as I can tell), it is a natural generation of the [Smirnov's deleted sequence topology](https://topology.pi-base.org/spaces/S000056). Indeed, if each of the intervals in $A$ is replaced by a point in the said interval, then the generated topology would be Smirnov's deleted sequence topology. (This is also the reason I named the topology deleted sequence of intervals topology.) Thus, the two topologies share many properties. However, it is distinct from Smirnov's deleted sequence topology in one important aspect - it is semiregular but not regular. Whence, it provides an example of a submetrizable semiregular space that is not regular. (See [Math StackExchange 4996729](https://math.stackexchange.com/questions/4996729).)

## Relationship to other spaces and properties

This space provides an example satisfying the search https://topology.pi-base.org/spaces?q=Submetrizable+%2B+Semiregular+%2B+not+Regular, which currently has no example on pi-base.

**Comment by Almanzoris** [comment]
Would be cool to have.

**Comment by prabau** [comment]
I suppose you meant $A$ = the union of the intervals $[1/3^n,2/3^n]$ ?

**Comment by david20000813** [comment]
@Almanzoris Thanks! I’m waiting to gain write access. Then I’m planning to write a PR to add this.

**Comment by david20000813** [comment]
@prabau Ah, the original intention was $[\frac{2}{3^n}, \frac{1}{3^{n-1}}]$. I accidentally flipped the two endpoints around. But yes, that works too. It doesn’t matter as long as it’s a sequence of non-degenerate closed intervals converging from one direction to $0$.

**Comment by david20000813** [comment]
The issue with endpoints is now fixed in the MSE answer.

**Comment by Almanzoris** [comment]
Yeah, I actually noticed that the endpoints were switched back then, but I didn't know if it was that or you meant the exponents to be the same. Anyways, I got the idea.

**Comment by david20000813** [comment]
Closed by #960
