### ISSUE TITLE
Trait Suggestion: Weak topology on separable Hilbert space (S21) is not a $k_1$-space (P140)

### ISSUE THREAD

**Issue by david20000813** [pi-base/data#928]
## Trait Suggestion

The space weak topology on separable Hilbert space ([S21](https://topology.pi-base.org/spaces/S000021)) is not a $k_1$-space ([P140](https://topology.pi-base.org/properties/P000140)), but this fact is not known to pi-Base today: https://topology.pi-base.org/spaces/S000021/properties/P000140

## Proof/References

A direct consequence of Theorem 1.3 in [1](https://arxiv.org/pdf/1502.00178v1).

**Comment by david20000813** [comment]
I was originally going to suggest the trait that S21 is not sequential, but since sequential spaces are $k_2$, the edited trait is stronger.

**Comment by david20000813** [comment]
A better source: G. Schlüchtermann, R. F. Wheeler, The Mackey dual of a Banach space, Noti de Matematica, XI (1991), 273–287.

The theorem is asserted at the start of Section 5 of the above paper. The DOI of the paper is [10.1285/I15900932V11P273](https://doi.org/10.1285/I15900932V11P273).

**Comment by StevenClontz** [comment]
Closed by #944
