### ISSUE TITLE
Trait Suggestion: The butterfly space (S143) is not simply connected (P200)

### ISSUE THREAD

**Issue by david20000813** [pi-base/data#931]
## Trait Suggestion

The butterfly space ([S143](https://topology.pi-base.org/spaces/S000143)) is not simply connected ([P200](https://topology.pi-base.org/properties/P000200)), but this fact is not known to pi-Base today:

https://topology.pi-base.org/spaces/S000143/properties/P000200

## Proof/References

Shown in MartianInvader’s [answer](https://math.stackexchange.com/a/4998680/465145) to [Math StackExchange 4998216](https://math.stackexchange.com/questions/4998216).

**Comment by GeoffreySangston** [comment]
I think we added it a few days ago. Perhaps there's a caching issue / pi-base needs to be [reset](https://topology.pi-base.org/dev) on your end? 

https://topology.pi-base.org/spaces/S000143/properties/P000200

**Comment by david20000813** [comment]
> I think we added it a few days ago. Probably pi-base needs to be [reset](https://topology.pi-base.org/dev) on your end by clicking the reset button there.
> 
> (Your link loads the page for me, and it links to MSE + asserts S143 is not simply connected.)

Oh yeah you’re right, it is already there. I thought I had synchronized before submitting this issue, but apparently not. Thanks! I’ll close this issue then.
