### ISSUE TITLE
Property Suggestion: Has a non-cut point (or Cut point space)

### ISSUE THREAD

**Issue by GeoffreySangston** [pi-base/data#939]
## Property Suggestion

A point $p \in X$ is called a *noncut point* if $X$ is connected and $p$ is not a [cut point](https://topology.pi-base.org/properties/P000204). I.e., $X$ and $X \backslash \\{p\\}$ are connected.

$X$ is a *Cut point space* if $X$ is nonempty, connected, and does not have a noncut point. Equivalently, $X$ is nonempty, connected, and every point is a cut point.

## Rationale

Engelking and Honari-Bahrampour, the references at  [Has a cut point (P204)](https://topology.pi-base.org/properties/P000204), define noncut point. Honari-Bahrampour defines cut point space. There is a [wikipedia page for cut point](https://en.wikipedia.org/wiki/Cut_point). danflapjax already has [a branch](https://github.com/pi-base/data/compare/main...cut-point) introducing this. 

## Relationship to other properties
It seems reasonable to consider adding either 'Has a noncut point' or 'Cut point space', but I'll just stick to 'Cut point space' here.

1. 'Cut point space => Has a cut point'. (Compare: '~Has cut point + Connected + ~Empty => Has a noncut point')

(Definition) 

2. 'Cut point space => ~Compact'. (Compare: Connected  + ~Empty + Compact => Has a noncut point)

 > [Honari-Bahrampour,  Corollary 3.10.] Let X be a cut-point space. Then X is non-compact.

3. 'Homogeneous + Has a cut point => Cut point space'. (Compare: 'Has a cut point + Has a noncut point => ~Homogeneous')

4. 'Cut point space => Has a closed point'. (Compare: Connected + ~Has a closed point => Has a noncut point)

> [Honari-Bahrampour, Theorem 3.7.] Let X be a cut-point space. Then the set of closed points of X is infinite.

This is related to 'Has a cut point + ~Has an isolated point => Has a closed point'.

## Remarks

- Engelking uses "noncut point". Honari-Bahrampour uses "non-cut point". Both non-cut point and noncut point seem common enough. (As are cut point space and cut-point space.)
- You can see on [Google scholar](https://scholar.google.com/scholar?start=0&q=%22cut+point+space%22&hl=en&as_sdt=0,21) that cut point space, cut-point space, cutpoint space all appear. There are 30 results.
- ["non-cut point"](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=%22non-cut+point%22&btnG=) has 294 results.
- The 'Has a cut point' property was introduced here https://github.com/pi-base/data/pull/936#issue-2681381592.
- 'Has a non-cut point' mentioned here https://github.com/pi-base/data/pull/302#issuecomment-2492395637

**Comment by prabau** [comment]
> X is a _Cut point space_ if X is connected and does not have a noncut point. Equivalently, X is connected, nonempty, and every point is a cut point.

To make the two formulations equivalent, wouldn't that require nonempty also in the first one, or in neither?

**Comment by prabau** [comment]
General remark: Not that I am pushing to introduce both "Has a non-cut point" and "cut-point space", but in some cases we have introduced "convenience properties" that are directly equivalent to a conjunction of properties or negated properties.  For example "Countably infinite = countable + not finite".

But working on the assumption we only add one of them for now, "cut-point space" is certainly a more targeted property, satisfied by a few select spaces.  "Has a non-cut point" is much more diffuse. 

Of the various theorems involving the two notions, would they look more natural or more interesting when phrased in term of one concept versus the other?  My completely uneducated guess would be that phrasing things in terms of "cut-point space" would be better in that respect.  Would that be your initial impression?

**Comment by GeoffreySangston** [comment]
I changed one of the theorems when I noticed it was implied by a stronger theorem on the list.

I added suggested alternatives for the 'Has a noncut point' variant (hopefully they're correct). I think I actually like 2 and 4 more with the 'Has a noncut point' version, but I'm not sure for the 3 version. I feel unqualified to really answer though since I haven't spent much time thinking about cut point spaces.

**Comment by danflapjax** [comment]
Maybe I'm not seeing in the right way, but "has a non-cut point" seems far less useful to me. Why would we care about whether one exists if the space isn't connected, for example? Also, theorems like "cut point space => not compact", "cut point space => infinite", and "cut point space => T0" are definitely more complicated to express via "has a non-cut point".

**Comment by prabau** [comment]
Not saying I want "has a non-cut point", but that property assumes "connected", right? Both "has a cut point" and "has a non-cut point" assume in their definition that the space is connected.

**Comment by danflapjax** [comment]
I missed that that was stated in the lead; the theorems gave connected as a separate term.

**Comment by prabau** [comment]
I re-read this discussion one more time, and it's hard to decide.  The notion of "has a non-cut point" is a classical one and appears in a lot of places.  "Cut point space" is a more recent thing, but it's used and is pretty descriptive for that restricted class of spaces.

What would you think of adding both properties, and for the theorems above, select the version that seems more natural?

**Comment by danflapjax** [comment]
I'm not sure it makes that much sense to do. Note that Cut point space <=> Connected + ~Has a cut point or equivalently  Thinking through how th, essentially every theorem

**Comment by danflapjax** [comment]
I'm not sure it makes that much sense to add both. Note that Cut point space <=> Connected + ~Empty + ~Has a non-cut point or equivalently Has a non-cut point <=> Connected + ~Empty + ~Cut point space. Thinking through how they relate to other properties, it looks like essentially every theorem is a direct assertion about cut point spaces, which gets more complicated by trying to express in terms of "Has a non-cut point". There just aren't really any properties that follow from it alone apart from the trivial conclusion of connectedness. This seems less desirable or useful to me.

**Comment by prabau** [comment]
We should choose one and go for it.  If want to have just "cut point space, that's fine with me.  @GeoffreySangston ?

**Comment by GeoffreySangston** [comment]
I'm happy with just 'cut point space'.
