### ISSUE TITLE
Property Suggestion: Has a closed point

### ISSUE THREAD

**Issue by GeoffreySangston** [pi-base/data#940]
## Property Suggestion

'Has a closed point': Some singleton $\\{x\\}$ of the space is closed.

## Rationale

This seems like a convenient and easily recognizable utility property. The concept of a closed point is common; e.g., in a common definition of [T1 space](https://topology.pi-base.org/properties/P000002).

Compare with [Has an isolated point (P139)](https://topology.pi-base.org/properties/P000139).

## Relationship to other properties

1. 'Has a closed point' implies ~Empty (P137)
2. $T_1$ (P002) + ~Empty (P137) implies Has a closed point
3. Has a cut point (P204) + ~Has an isolated point (P139) implies Has a closed point
 - [[Honari-Bahrampour, Theorem 3.2]](https://www.ams.org/journals/proc/1999-127-09/S0002-9939-99-04839-X/S0002-9939-99-04839-X.pdf)
4. Ultraconnected (P040) + Has a cut point (P204) implies Has a closed point
5. Ultraconnected + Has a closed point implies Has a focal point
 - Compare 4, 5 with [T618](https://topology.pi-base.org/theorems/T000618). The impetus for this 'Issue' was danflapjax's comment https://github.com/pi-base/data/pull/936#issuecomment-2493042608
6. Homogeneous (P086) + Has a closed point implies $T_1$ (P002).

(I won't try to exhaust the entire list. Surely there are many others, and feel free to edit it any that you see. Hopefully this is enough to begin the discussion though.)

## Other remarks

- [S48|P86](https://topology.pi-base.org/spaces/S000048/properties/P000086) would get naturally deduced, because this space is not $T_1$, but every point besides the zero ideal is a closed point. (Though this might get deduced after some other properties which still need to be added to this one get added.)

**Comment by prabau** [comment]
Yeah, I have often thought this would be a nice thing to have.

@StevenClontz Would you agree?

**Comment by prabau** [comment]
I particularly like the relationship (5) that is the dual of:
T597: Hyperconnected + Has an isolated point ==> Has a generic point.

**Comment by Almanzoris** [comment]
@GeoffreySangston I have read the suggestion again and I agree on incorporating the property and the results.

**Comment by prabau** [comment]
I would imagine several of the existing theorems will also be able to be strengthened or simplified using the new notion, or replaced by one of the suggested theorems above.

**Comment by StevenClontz** [comment]
> Yeah, I have often thought this would be a nice thing to have.
> 
> @StevenClontz Would you agree?

Seems reasonable to me at a glance. I'd like to see the PR that introduces it to demonstrate its utility: define the property, add whatever theorems seem most useful/obvious, and clean up traits for one (not all!) space using those new theorems.

**Comment by david20000813** [comment]
Closed by #965 and #973
