### ISSUE TITLE
References

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#95]
Right now the pi-base viewer supports three kinds of references:

- DOI (`doi:`)
- Mathematical Reviews (`mr:`)
- Wikipedia (`wikipedia:`)

We've started to use the following references, and the viewer will eventually display them:

- Math.StackExchange (`mathse:`)
- Math Overview (`mo:`)

What other references should we support? We've avoided supporting generic URLs historically to emphasize that we want things subject to some sort of peer review. But @prabau suggests that some JSTOR references don't have DOIs or MR numbers. Do we add JSTOR? Or is there another broad tagging mechanism like DOI/MR that would cover that use case?

**Comment by prabau** [comment]
Actually, for the particular reference that initiated this discussion (https://www.jstor.org/stable/26453423) there was no DOI/MR, but I just checked that there is a Zentralblatt ref (https://zbmath.org/?q=an%3A1030.54019).  If we don't want to allow naked jstor refs, that may be another option.

**Comment by ccaruvana** [comment]
I think jstor might be appropriate. I noticed that Theorem 245 and Property 130 both have a proposed doi that doesn't work. I took a look and found the article with a jstor stable link: https://www.jstor.org/stable/24340250
However, this article has no doi (at least, I couldn't find one even in the bibtex generated by jstor) nor could I find MR or Zentralblatt.

**Comment by StevenClontz** [comment]
Definitely:

- Zentralblatt `zbmath:`

**Comment by prabau** [comment]
Chris and I discussed in the zoom meeting and we thing this can be closed.
