### ISSUE TITLE
Is S195 named after a standard construction? Should S195 be renamed?

### ISSUE THREAD

**Issue by GeoffreySangston** [pi-base/data#968]
[S195](https://topology.pi-base.org/spaces/S000195/references) is named *Join of cofinite and left-ray topologies on* $\omega_1$. I can't seem to find the referenced paper, by Nyikos. Is it defined there with this name? If this kind of join is a standard topological concept, could we include another reference to the construction in the reference list? I didn't find this concept in Munkres, Steen-Seebach, or Engelking. 

Also, the [join of topological spaces](https://en.wikipedia.org/wiki/Join_(topology)) (defined on page 9 of Hatcher's algebraic topology book) has a different standard meaning than what appears here. So if the 'Join' from the name of S195 is not a standard construction, should we rename S195 so it doesn't clash with this other standard operation?

There's a different kind of join in topology, in addition to the standard one. Barmak defines the *non-Hausdorff join* of $T_0$ spaces $X$ and $Y$ as $X \sqcup Y$ with the topology (defined in terms of the specialization order) $x \le y$ for every $x \in X$ and $y \in Y$, and otherwise the same orders on $X$ and $Y$. This join is also not the one from S195 though.

I brought this up because S195 is not connected, but its factors are contractible, so the operation doesn't seem to function how I expect a join to.

**Comment by danflapjax** [comment]
Join in this context is referring to the the operation in the lattice of topologies, e.g. see [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_topologies#Lattice_of_topologies). Note that the name specifically refers to the "join of ... _topologies_", not spaces, so those other types of joins don't apply, strictly speaking.

**Comment by GeoffreySangston** [comment]
> Note that the name specifically refers to the "join of ... _topologies_", not spaces, so those other types of joins don't apply, strictly speaking. 

This what I would view as correct outside of pi-base. The problem however is pi-base has a few dozen spaces named '<blank> topology on <blank>'. So pi-base already has the convention of identifying the topology with the space. Specifically, pi-base has ' Cofinite topology on $\omega$ ' (S15) and 'Left ray topology on $\omega$' (S199). So it does seem ambiguous for this other name to now use 'Cofinite topology on $\omega_1$' and 'Left ray topology on $\omega$' to refer to the topologies instead of the spaces.

**Comment by prabau** [comment]
Bit of history, we chose that name because it was the shortest we could come up with while also giving a completely non-ambiguous description of the topology (but we did not have anything about algebraic topology at that time).

**Comment by prabau** [comment]
> This what I would view as correct outside of pi-base. The problem however is pi-base has a few dozen spaces named 'blank topology on blank'. So pi-base already has the convention of identifying the topology with the space in names. Specifically, pi-base has ' Cofinite topology on ω ' (S15) and 'Left ray topology on ω ' (S199). So it does seem ambiguous for this other name to now use 'Cofinite topology on ω 1 ' and 'Left ray topology on ω ' to refer to the topologies instead of the spaces.

I actually kind of agree with you.  It's a little sloppy to name a space as a "topology".  S&S were already guilty of that, I think, and we just followed suit.

**Comment by danflapjax** [comment]
> The problem however is pi-base has a few dozen spaces named 'blank topology on blank'. So pi-base already has the convention of identifying the topology with the space in names.

Huh, fair point. I guess I hadn't considered that topologies and spaces were being conflated in that way. I don't think that naming style is unclear, but I suppose it also isn't quite technically correct. Perhaps it is worth changing. To me, the main benefit of the current style though is that it puts the description of the topology first, which I see as a plus for quick readability in a long list; the important part of "Discrete topology on the real numbers" seems easier to glean than if it were "Real numbers with the discrete topology". Perhaps there is a phrasing that achieves the best of both worlds, but I certainly haven't come up with it yet.

> Though since it does correspond to a standard operation, I don't think it should be changed. Maybe we could just add the link to the construction in the description, like prabau says?

That sounds perfectly reasonable :+1:

**Comment by prabau** [comment]
Calling a space "Space on the set X with the topology that is the join of the topologies from {...} and {...}" would be a mouthful!

**Comment by Moniker1998** [comment]
II think the name of this space should be changed
