### ISSUE TITLE
Space Suggestion: Sphere, $S^2$, Two-dimensional sphere

### ISSUE THREAD

**Issue by GeoffreySangston** [pi-base/data#981]
## Space Suggestion

Let $X$ be $S^2 := \\{x \in \mathbb{R}^3 : \left \| x \right \|_2 = 1\\}$, where $\left\| x \right\|_2$ denotes the standard Euclidean norm of $x$.

$X$ is homeomorphic to:

- One-point compactification of [Euclidean Plane R2](https://topology.pi-base.org/spaces/S000176)
- [Suspension](https://en.wikipedia.org/wiki/Suspension_(topology)) of [Circle](https://topology.pi-base.org/spaces/S000170)
- Double cover of [Projective Plane](https://github.com/pi-base/data/issues/893#issue-2647576807) (<- Link to previous open Issue)

## Rationale

This space appears in almost every book about and adjacent to topology. E.g., Engelking example 2.3.9. Also mentioned a few times, e.g., https://github.com/pi-base/data/issues/851#issuecomment-2453138651.

## Relationship to other spaces and properties

Will give an example for the following presently empty searches:
 - [π-Base, Search for `~Has a group topology + topological n-manifold + ~empty`](https://topology.pi-base.org/spaces?q=%7EHas+a+group+topology+%2B+topological+n-manifold+%2B+%7Eempty)
 - [π-Base, Search for `compact + Simply connected + ~contractible + locally connected + ~empty`](https://topology.pi-base.org/spaces?q=compact+%2B+Simply+connected+%2B+%7Econtractible+%2B+locally+connected+%2B+%7Eempty)

Will be the 6th example of:
 - [π-Base, Search for `Topological $n$-manifold + connected`](https://topology.pi-base.org/spaces?q=Topological+%24n%24-manifold+%2B+connected)

**Comment by david20000813** [comment]
The main properties to add would seem to be:

1. Topological $n$-manifold;
2. Compact;
3. Simply connected;
4. ~Contractible;
5. ~Has a group topology;
6. Homogeneous;
7. ~Empty.

**Comment by yhx-12243** [comment]
> The main properties to add would seem to be:
> 
> 1. Topological 
>      n
>    -manifold;
> 2. Compact;
> 3. Simply connected;
> 4. ~Contractible;
> 5. ~Has a group topology;
> 6. Homogeneous;
> 7. ~Empty.

8. ~Fixed point property.
