### ISSUE TITLE
Space Suggestion: Use "Fréchet space R^ω" as the default name for S30

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#986]
## Space Suggestion

Use "Fréchet space $\mathbb R^\omega$" as the default name for [S30](https://topology.pi-base.org/spaces/S000030).

## Rationale

While there are numerous aliases and characterizations for this space, the most elegant (in terms of the topological properties we model in $\pi$-Base) is probably the Tychonoff product of countably-many copies of the real line.

See also discussion at #956.

**Comment by prabau** [comment]
It would be a little bit of a shame to lose the Hilbert space from the main list, but your point has some validity.
Before making a decision, note also that most of the proofs for the asserted traits assume the Hilbert space incarnation.

Soliciting more input from other contributors.

**Comment by david20000813** [comment]
There is technically some confusion about the name "Fréchet space", coming from someone with a background in functional analysis. That confusion is sort of already there in the description for S30, namely, in the line "... any infinite-dimensional separable Banach space or separable Fréchet space is homeomorphic to...", where the term "Fréchet space" means very different things than $\mathbb{R}^\omega$. Instead, it refers to a locally convex topological vector space whose topology is completely metrizable. But I do agree that, from a purely topological perspective, $\mathbb{R}^\omega$ is sort of the most elegant one. Whether causing confusion for functional analysts is an important concern or not is debatable.

**Comment by prabau** [comment]
Have just $\mathbb R^\omega$ in the title?

**Comment by david20000813** [comment]
@prabau I don’t think any space in pi-Base currently has just symbols as its name. There’s always some English description attached. Maybe we can say “Countable product of reals $\mathbb{R}^\omega$”, parallel with [S107](https://topology.pi-base.org/spaces/S000107)?

**Comment by GeoffreySangston** [comment]
I vote for @david20000813's last suggestion, "Countable product of reals $\mathbb{R}^\omega$"

**Comment by prabau** [comment]
And if we go with the suggested space as a main name, I guess for the proofs of traits that rely on Hilbert space, we can either replace them with an easy direct proof for $\mathbb{R}^\omega$ if there is one, or add "In its incarnation as the separable Hilbert space $\ell^2$, blah blah" or something of the kind, relying on the homeomorphisms presented in the README file.

**Comment by StevenClontz** [comment]
"Countable product of reals $\mathbb R^\omega$" sounds great to me. [Note Frechet also means $T_1$.](https://topology.pi-base.org/properties/P000002)

I'll make a PR for everyone's consideration.

**Comment by StevenClontz** [comment]
Er, well, we should wait for #975 first (there's no rush here).

**Comment by StevenClontz** [comment]
> After further research, I realized there is even one more point of confusion: [Fréchet Urysohn spaces](https://topology.pi-base.org/properties/P000080) were called Fréchet spaces in some sources.

Ooh, we should add Fréchet as an alias here; I've see this as well.

**Comment by david20000813** [comment]
@StevenClontz [This paper](https://doi.org/10.4064%2Ffm-77-2-95-98) mentions three different names for Fréchet Urysohn spaces: Fréchet spaces, closure-sequential spaces, and neighborhood-sequential (or $N$-sequential) spaces.

**Comment by prabau** [comment]
> > After further research, I realized there is even one more point of confusion: [Fréchet Urysohn spaces](https://topology.pi-base.org/properties/P000080) were called Fréchet spaces in some sources.
> 
> Ooh, we should add Fréchet as an alias here; I've see this as well.

How about _not_ adding Frechet as an alias for Frechet-Urysohn?  Someone who types Frechet in a search will see Frechet-Urysohn displayed already, so the clear choice to explore will be obvious.

But maybe we should add a hyphen: Fréchet-Urysohn?  Seems to be more common.

**Comment by StevenClontz** [comment]
I like the switch to Fréchet-Urysohn for the main name. 

I still think adding the alias Fréchet is wise: if someone's reading an older paper and sees "Fréchet" they may not think to look at Fréchet-Urysohn without the alias. 

I'll mock up a PR and we can see how we feel.
