### ISSUE TITLE
For P200 (simply connected), I think one also needs to mention the space is path connected

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/data#998]
> For P200 (simnply connected), I think one also needs to mention the space is path connected, as Hatcher Prop 1.14 is only about the fundamental group.  (Otherwise it's kind of circular: Path connected is now derived from simply connected.)

> Actually, I can do that suggested change tomorrow, together with something else.

_Originally posted by @prabau in https://github.com/pi-base/data/issues/988#issuecomment-2510749240_

**Comment by prabau** [comment]
Thanks, but not sure why we need an issue here.  I was going to do the PR anyway. :-)

**Comment by StevenClontz** [comment]
Habit for anything that shows up in a closed PR so ensure it's not lost.
